const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const box={exports:{}};vm.runInNewContext(fs.readFileSync('assets/memory-engine.js','utf8'),{module:box});const E=box.exports,recordsBox={exports:{}};vm.runInNewContext(fs.readFileSync('assets/memory-records.js','utf8'),{module:recordsBox});const R=recordsBox.exports;let seed=7;const rng=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
for(const size of E.COUNTS)for(let run=0;run<20;run++){
 let s=E.create(size,rng,0),now=0;assert.equal(s.deck.length,size);const ids=[...new Set(s.deck)];assert.equal(ids.length,size/2);assert.ok(ids.every(id=>s.deck.filter(x=>x===id).length===2));assert.equal(s.remainingMs,E.SECONDS[size]*1000);
 for(const id of ids){const pair=s.deck.map((x,i)=>x===id?i:-1).filter(i=>i>=0);s=E.act(s,{type:'flip',index:pair[0]},now).state;const same=E.act(s,{type:'flip',index:pair[0]},now);assert.equal(same.state.flips,s.flips);s=E.act(s,{type:'flip',index:pair[1]},now).state;now+=650;s=E.act(s,{type:'tick'},now).state;}
 assert.equal(s.phase,'won');assert.equal(s.flips,size);assert.equal(s.attempts,size/2);assert.equal(s.combo,size/2);assert.equal(s.matched.length,size);assert.equal(s.shields,E.SHIELDS[size]);const terminal=E.act(s,{type:'flip',index:0},now+999999);assert.equal(terminal.state.score,s.score);assert.equal(terminal.state.phase,'won');assert.equal(terminal.effects.length,0);
}
let s=E.create(16,()=>0,0),first=0,other=s.deck.findIndex(x=>x!==s.deck[first]);s=E.act(s,{type:'flip',index:first},0).state;s=E.act(s,{type:'flip',index:other},0).state;assert.equal(s.phase,'resolving');const third=s.deck.findIndex((_,i)=>i!==first&&i!==other);s=E.act(s,{type:'flip',index:third},100).state;assert.equal(s.open.length,2);assert.equal(s.flips,2);
s=E.act(s,{type:'pause'},500).state;const left=s.remainingMs,reveal=s.revealMs;s=E.act(s,{type:'tick'},200000).state;assert.equal(s.remainingMs,left);assert.equal(s.revealMs,reveal);s=E.act(s,{type:'resume'},200000).state;s=E.act(s,{type:'tick'},200600).state;assert.equal(s.open.length,0);assert.equal(s.shields,15);assert.equal(s.combo,0);
let dying=E.create(16,()=>0,0);dying.shields=1;dying=E.act(dying,{type:'flip',index:first},0).state;dying=E.act(dying,{type:'flip',index:other},0).state;const ended=E.act(dying,{type:'tick'},1100);assert.equal(ended.state.phase,'lost');assert.equal(ended.state.reason,'shield');assert.equal(ended.state.shields,0);assert.equal(ended.effects.filter(e=>e.kind==='lost').length,1);
const timed=E.act(E.create(52,rng,0),{type:'flip',index:0},300000);assert.equal(timed.state.phase,'lost');assert.equal(timed.state.reason,'time');assert.equal(timed.state.flips,0);assert.throws(()=>E.create(20));assert.throws(()=>E.create(17));assert.throws(()=>E.create(62));
const last=E.create(16,()=>0,0);last.matched=last.deck.map((_,i)=>i).filter(i=>last.deck[i]!==last.deck[0]);last.remainingMs=1;const lastPair=last.deck.map((id,i)=>id===last.deck[0]?i:-1).filter(i=>i>=0);const one=E.act(last,{type:'flip',index:lastPair[0]},0).state;assert.equal(E.act(one,{type:'flip',index:lastPair[1]},0).state.phase,'won','Last pair completes before the animation even with less than one second left');
console.log('PASS: all five deck sizes contain exact pairs; matches, combo scoring, click locks, timed failure, shield failure, pause/resume and terminal rewards behave correctly.');

function boot(options={}){const nodes=new Map(),frames=new Map(),timers=new Map(),events={},docEvents={},soundEvents=[],imageRequests=[],canvasCalls=[],storage=options.storage||new Map();const viewportEvents={},browserWindow={},boardBounds={width:options.boardWidth??((options.width||390)-20),height:options.boardHeight??((options.height||844)-200)};let now=0,id=0,document;function element(){let text='',className='';const cls=new Set();return {children:[],style:{setProperty(k,v){this[k]=String(v)},getPropertyValue(k){return this[k]||''}},dataset:{},attributes:{},hidden:false,disabled:false,checked:false,open:false,
 textWrites:0,get src(){return this.url||''},set src(value){this.url=value;imageRequests.push(this);if(!options.imagesPending){this.settled=true;this.onload?.();}},removeAttribute(k){delete this.attributes[k];if(k==='src')this.url='';},get className(){return className},set className(v){className=v},classList:{toggle(k,on){on?cls.add(k):cls.delete(k)},add(k){cls.add(k)},remove(k){cls.delete(k)},contains(k){return cls.has(k)}},
 appendChild(n){this.children.push(n);n.parentElement=this;return n},append(...ns){ns.forEach(n=>this.appendChild(n))},replaceChildren(...ns){text='';this.children=[];this.append(...ns)},setAttribute(k,v){this.attributes[k]=v},getAttribute(k){return this.attributes[k]},get textContent(){return text+this.children.map(c=>c.textContent).join('')},set textContent(v){this.textWrites++;text=String(v);this.children=[]},focus(){document.activeElement=this},scrollIntoView(){},click(){if(!this.disabled)this.onclick?.()},showModal(){this.open=true},close(){this.open=false},addEventListener(k,fn){this['event-'+k]=fn},getBoundingClientRect(){return {left:0,top:0,width:100,height:100}},getContext(){return options.canvas?{setTransform(){},clearRect(){canvasCalls.push('clear')},fillRect(){canvasCalls.push('draw')}}:null}};}
 const get=k=>{if(!nodes.has(k))nodes.set(k,element());return nodes.get(k)};document={body:element(),getElementById:get,createElement:element,createElementNS:element,addEventListener(k,fn){docEvents[k]=fn},hidden:false};get('timeValue').parentElement=element();get('memorySound').checked=true;get('memoryMusic').checked=true;for(const [id,file] of [['resultWinArt','win'],['resultLossArt','loss']])get(id).dataset.src='/assets/memory-result-'+file+'.webp';get('memoryBoard').getBoundingClientRect=()=>({...boardBounds,left:0,top:0});const math=Object.create(Math);math.random=()=>.42;
 class SpriteImage{set src(value){this.url=value;imageRequests.push(this);if(!options.imagesPending){this.settled=true;this.onload();}}}
 vm.runInNewContext(fs.readFileSync('assets/memory-ui.js','utf8'),{window:Object.assign(browserWindow,{OrbitMemory:E,OrbitRecords:R,OrbitAudio:{create(){return {activate(){soundEvents.push(['activate']);return Promise.resolve();},play(v){soundEvents.push(['play',v])},setEnabled(v){soundEvents.push(['effects',v])},setMusic(v){soundEvents.push(['music',v])},startMusic(v){soundEvents.push(['start',v])},stopMusic(){soundEvents.push(['stop'])},setTension(v){soundEvents.push(['tension',v])},suspend(){soundEvents.push(['suspend'])},dispose(){soundEvents.push(['dispose'])}}}},Image:SpriteImage,localStorage:{getItem(key){if(options.storageBlocked)throw Error('Storage unavailable');return storage.get(key)||null},setItem(key,value){if(options.storageBlocked)throw Error('Storage unavailable');storage.set(key,value)}},innerWidth:options.width||390,innerHeight:options.height||844,devicePixelRatio:1,visualViewport:{height:options.visualHeight||options.height||844,scale:1,addEventListener(k,fn){viewportEvents[k]=fn}},matchMedia(){return {matches:options.reduced!==false,addEventListener(){}}},addEventListener(k,fn){events[k]=fn}}),document,Math:math,performance:{now:()=>now},requestAnimationFrame(fn){const key=++id;frames.set(key,fn);return key},cancelAnimationFrame(key){frames.delete(key)},setTimeout(fn,delay){const key=++id;timers.set(key,{fn,at:now+delay});return key},clearTimeout(key){timers.delete(key)}});
 return {get,docEvents,document,events,frames,timers,boardBounds,resize(width,height,boardWidth=width-20,boardHeight=height-200){browserWindow.innerWidth=width;browserWindow.innerHeight=height;browserWindow.visualViewport.height=height;boardBounds.width=boardWidth;boardBounds.height=boardHeight;events.resize();},visualResize(height,boardHeight,scale=1){browserWindow.visualViewport.height=height;browserWindow.visualViewport.scale=scale;boardBounds.height=boardHeight;viewportEvents.resize();},soundEvents,imageRequests,canvasCalls,storage,settleImages(ok=true){for(const img of imageRequests)if(!img.settled){img.settled=true;ok?img.onload():img.onerror();}},step(ms){now+=ms;const callbacks=[...frames.values()];frames.clear();callbacks.forEach(fn=>fn(now));let count=0;for(;;){const due=[...timers].filter(([,t])=>t.at<=now);if(!due.length)break;assert.ok(++count<1000,'Timers must not spin');for(const [key,t] of due)if(timers.delete(key))t.fn();}}};
}
for(const size of E.COUNTS){const ui=boot();ui.get('memoryCounts').children.find(b=>Number(b.dataset.count)===size).click();const planned=Number(ui.get('setupCards').textContent),rules=E.rules(planned);ui.get('memoryStart').click();assert.equal(ui.get('memoryGrid').children.length,planned);assert.equal(ui.get('setupShield').textContent,String(rules.shields));assert.equal(ui.get('shieldValue').textContent,rules.shields+'/'+rules.shields);assert.equal(ui.get('setupTime').textContent, String(Math.floor(rules.seconds/60)).padStart(2,'0')+':'+String(rules.seconds%60).padStart(2,'0'));ui.get('memoryPause').click();const before=ui.get('timeValue').textContent;ui.step(300000);assert.equal(ui.get('timeValue').textContent,before);assert.equal(ui.get('missionDialog').open,true);ui.get('dialogResume').click();ui.step(1000);assert.notEqual(ui.get('timeValue').textContent,before);ui.document.hidden=true;ui.docEvents.visibilitychange();assert.equal(ui.get('missionDialog').open,true);}
const ui=boot();ui.get('memoryStart').click();const deck=E.create(16,()=>.42,0).deck;for(const id of new Set(deck)){for(let i=0;i<deck.length;i++)if(deck[i]===id)ui.get('memoryGrid').children[i].click();ui.step(650);}ui.step(1);assert.match(ui.get('dialogTitle').textContent,/重新上線/);assert.equal(ui.get('missionDialog').open,true);ui.get('dialogRestart').click();assert.equal(ui.get('flipsValue').textContent,'0');assert.equal(ui.get('scoreValue').textContent,'0');ui.step(180000);assert.match(ui.get('dialogTitle').textContent,/中止/);assert.equal(ui.get('missionDialog').open,true);
console.log('PASS: real memory UI starts all sizes, pauses and hides cards, resumes timing, auto-pauses in background, shows victory/timeout results and resets counters on restart.');
const themeKey='learning-planet-memory-theme-v1',themeUI=boot();
assert.equal(themeUI.document.body.dataset.cardTheme,'C');assert.equal(themeUI.get('memoryThemes').children.filter(b=>b.getAttribute('aria-pressed')==='true').length,1);
for(const theme of ['A','B','C']){themeUI.get('memoryThemes').children.find(b=>b.dataset.theme===theme).click();assert.equal(themeUI.document.body.dataset.cardTheme,theme);assert.equal(themeUI.storage.get(themeKey),theme);assert.equal(boot({storage:themeUI.storage}).document.body.dataset.cardTheme,theme);}
assert.equal(boot({storage:new Map([[themeKey,'invalid']])}).document.body.dataset.cardTheme,'C');
const denied=boot({storageBlocked:true});denied.get('memoryThemes').children[1].click();denied.get('memoryStart').click();assert.equal(denied.document.body.dataset.cardTheme,'B');assert.equal(denied.get('memoryGrid').children.length,16);
const allArt=boot({width:1440,height:900});allArt.get('memoryCounts').children[4].click();allArt.get('memoryStart').click();const fullDeck=E.create(allArt.get('memoryGrid').children.length,()=>.42,0).deck,bySymbol=new Map();
allArt.get('memoryGrid').children.forEach((card,i)=>{const sprite=card.children[0].children[1].children[1],appearance=sprite.className+'|'+sprite.style.backgroundPosition,id=fullDeck[i];if(bySymbol.has(id))assert.equal(appearance,bySymbol.get(id),'Matching cards must show identical equipment');else bySymbol.set(id,appearance);assert.match(card.getAttribute('aria-label'),/未翻開/);});
assert.equal(new Set(bySymbol.values()).size,fullDeck.length/2,'All equipment symbols must have distinct artwork');
const waiting=boot({imagesPending:true});assert.equal(waiting.get('memoryStart').disabled,true);waiting.get('memoryStart').click();waiting.step(19000);assert.equal(waiting.get('memoryGrid').children.length,0);waiting.settleImages();assert.equal(waiting.get('memoryStart').disabled,false);waiting.get('memoryStart').click();assert.equal(waiting.get('timeValue').textContent,'03:00','Loading must not consume mission time');
const failedArt=boot({imagesPending:true});failedArt.settleImages(false);assert.equal(failedArt.get('memoryStart').getAttribute('aria-label'),'重新載入卡牌');failedArt.get('memoryStart').click();failedArt.settleImages();failedArt.get('memoryStart').click();assert.equal(failedArt.get('memoryGrid').children.length,16);
const stalledArt=boot({imagesPending:true});stalledArt.step(20000);assert.equal(stalledArt.get('memoryStart').disabled,false);assert.match(stalledArt.get('artworkStatus').textContent,/重試/);assert.equal(stalledArt.get('memoryGrid').children.length,0);
console.log('PASS: A/B/C theme selection defaults to C, persists safely, keeps 30 distinct matching images, and waits for artwork with retry on failure or timeout.');
const musicUI=boot();assert.equal(musicUI.soundEvents.length,0,'Home opens silently');musicUI.get('memoryStart').click();assert.ok(musicUI.soundEvents.some(([name,reset])=>name==='start'&&reset===true));musicUI.get('memoryMusic').checked=false;musicUI.get('memoryMusic').onchange();assert.deepEqual(musicUI.soundEvents.at(-1),['music',false]);musicUI.get('memoryPause').click();assert.equal(musicUI.soundEvents.at(-1)[0],'suspend');musicUI.get('dialogResume').click();assert.ok(musicUI.soundEvents.some(([name,reset])=>name==='start'&&reset===undefined));musicUI.step(170000);assert.ok(musicUI.soundEvents.some(([name,value])=>name==='tension'&&value>.7));musicUI.step(10000);assert.ok(musicUI.soundEvents.some(([name])=>name==='stop'));musicUI.get('dialogMenu').click();assert.equal(musicUI.soundEvents.at(-1)[0],'suspend');
console.log('PASS: game controls start music only in a mission, pause/resume with the game, update final-countdown tension and stop at results/menu.');
// The duration bounds preserve the original half-minute recommendations.
for(const seconds of [180,210,240,270,300,360,420,480,540,570,600]){
 const custom=E.create(24,()=>.42,0,seconds);assert.equal(E.act(custom,{type:'tick'},seconds*1000-1).state.phase,'playing');assert.equal(E.act(custom,{type:'tick'},seconds*1000).state.reason,'time');
}
for(const invalid of [0,179,601,Infinity,NaN,'300'])assert.throws(()=>E.create(16,()=>.42,0,invalid));
let unlimited=E.create(16,()=>.42,0,null);unlimited=E.act(unlimited,{type:'tick'},9999999).state;assert.equal(unlimited.remainingMs,null);assert.equal(unlimited.phase,'playing');
let unlimitedNow=9999999;for(const symbol of new Set(unlimited.deck)){for(const i of unlimited.deck.map((id,i)=>id===symbol?i:-1).filter(i=>i>=0))unlimited=E.act(unlimited,{type:'flip',index:i},unlimitedNow).state;unlimitedNow+=650;unlimited=E.act(unlimited,{type:'tick'},unlimitedNow).state;}
assert.equal(unlimited.phase,'won');assert.equal(unlimited.bonus,unlimited.shields*10);assert.ok(Number.isFinite(unlimited.score));
let noTimeShield=E.create(16,()=>.42,0,null);noTimeShield.shields=1;const different=noTimeShield.deck.findIndex(id=>id!==noTimeShield.deck[0]);noTimeShield=E.act(noTimeShield,{type:'flip',index:0},0).state;noTimeShield=E.act(noTimeShield,{type:'flip',index:different},0).state;assert.equal(E.act(noTimeShield,{type:'tick'},1100).state.reason,'shield');
const timeUI=boot();assert.equal(timeUI.get('timeMinus').disabled,true);for(let i=0;i<7;i++)timeUI.get('timePlus').click();assert.equal(timeUI.get('memoryTimeValue').textContent,'10:00');timeUI.get('timePlus').click();assert.equal(timeUI.get('setupTime').textContent,'∞');assert.equal(timeUI.get('timePlus').disabled,true);timeUI.get('timeMinus').click();assert.equal(timeUI.get('memoryTimeValue').textContent,'10:00');timeUI.get('timePlus').click();timeUI.get('memoryStart').click();timeUI.step(9999999);assert.equal(timeUI.get('timeValue').textContent,'∞');assert.equal(timeUI.get('missionDialog').open,false);assert.equal(timeUI.get('timeValue').parentElement.classList.contains('critical'),false);assert.equal(timeUI.soundEvents.filter(([name])=>name==='tension').at(-1)[1],0);
timeUI.get('memoryRestart').click();timeUI.get('dialogRestart').click();assert.equal(timeUI.get('timeValue').textContent,'∞','Retry retains the chosen duration');timeUI.get('memoryPause').click();timeUI.get('dialogMenu').click();timeUI.get('memoryCounts').children[1].click();assert.equal(timeUI.get('setupTime').textContent,'03:30');timeUI.get('timePlus').click();assert.equal(timeUI.get('setupTime').textContent,'04:30');timeUI.get('timeMinus').click();timeUI.get('timeMinus').click();assert.equal(timeUI.get('setupTime').textContent,'03:00');assert.equal(timeUI.get('timeMinus').disabled,true);
for(let i=0;i<7;i++)timeUI.get('timePlus').click();timeUI.get('memoryStart').click();assert.equal(timeUI.get('timeValue').textContent,'10:00');timeUI.step(600000);assert.equal(timeUI.get('missionDialog').dataset.outcome,'lost');
console.log('PASS: +/- duration controls keep recommended defaults, enforce 3–10 minutes, support unlimited time, retain retry settings, and preserve shield failure and finite scoring.');
function solveUI(app){const deck=E.create(16,()=>.42,0).deck;for(const symbol of new Set(deck)){for(let i=0;i<deck.length;i++)if(deck[i]===symbol)app.get('memoryGrid').children[i].click();app.step(650);}}
const intro=boot({reduced:false});intro.get('memoryStart').click();const originalCards=intro.get('memoryGrid').children;intro.get('memoryStart').click();assert.equal(intro.get('memoryGrid').children,originalCards,'Double launch cannot rebuild the mission');assert.equal(intro.get('launchDialog').open,true);intro.step(2399);assert.equal(intro.get('timeValue').textContent,'03:00');intro.get('memoryGrid').children[0].click();assert.equal(intro.get('flipsValue').textContent,'0','The deck is locked during arrival');intro.step(1);assert.equal(intro.get('launchDialog').open,false);assert.equal(intro.get('timeValue').textContent,'03:00');intro.step(1000);assert.equal(intro.get('timeValue').textContent,'02:59');
const skip=boot({reduced:false});skip.get('memoryStart').click();skip.step(400);skip.get('launchSkip').click();skip.get('memoryGrid').children[0].click();assert.equal(skip.get('flipsValue').textContent,'1');skip.step(2000);assert.equal(skip.get('flipsValue').textContent,'1','A canceled launch callback cannot restart the game');assert.equal(skip.get('timeValue').textContent,'02:58');
const escape=boot({reduced:false});escape.get('memoryStart').click();escape.events.keydown({key:'Escape',preventDefault(){}});assert.equal(escape.get('launchDialog').open,false);assert.equal(escape.get('missionDialog').open,false,'Escape skips arrival without opening pause');escape.get('memoryGrid').children[0].click();assert.equal(escape.get('flipsValue').textContent,'1');
for(const event of ['visibilitychange','pagehide']){const background=boot({reduced:false});background.get('memoryStart').click();if(event==='visibilitychange'){background.document.hidden=true;background.docEvents.visibilitychange();}else background.events.pagehide();background.step(300000);assert.equal(background.get('launchDialog').open,false);assert.match(background.get('dialogTitle').textContent,/暫停/);assert.equal(background.get('timeValue').textContent,'03:00');background.document.hidden=false;background.get('dialogResume').click();background.step(1000);assert.equal(background.get('timeValue').textContent,'02:59');}
const resultUI=boot({reduced:false});resultUI.get('memoryStart').click();resultUI.get('launchSkip').click();solveUI(resultUI);assert.equal(resultUI.get('missionDialog').open,false);assert.equal(resultUI.soundEvents.some(([name,kind])=>name==='play'&&kind==='won'),false,'End sound waits for the result animation');resultUI.step(50);assert.equal(resultUI.get('missionDialog').dataset.outcome,'won');assert.equal(resultUI.get('resultScene').hidden,false);assert.equal(resultUI.get('dialogRestart').hidden,false);assert.equal(resultUI.get('dialogMenu').hidden,false);resultUI.step(10000);assert.equal(resultUI.soundEvents.filter(([name,kind])=>name==='play'&&kind==='won').length,1);resultUI.get('dialogRestart').click();resultUI.get('launchSkip').click();resultUI.get('memoryPause').click();assert.equal(resultUI.get('resultScene').hidden,true,'Pause dialogs do not inherit the result illustration');
const stale=boot({reduced:false});stale.get('memoryStart').click();stale.get('launchSkip').click();stale.step(180000);stale.get('memoryRestart').click();stale.get('dialogRestart').click();stale.get('launchSkip').click();stale.step(700);assert.equal(stale.get('missionDialog').open,false);assert.equal(stale.soundEvents.some(([name,kind])=>name==='play'&&kind==='lost'),false,'A reset cancels the previous ending and its sound');
const hiddenResult=boot({reduced:false});hiddenResult.get('memoryStart').click();hiddenResult.get('launchSkip').click();hiddenResult.step(180000);hiddenResult.document.hidden=true;hiddenResult.docEvents.visibilitychange();hiddenResult.step(700);assert.equal(hiddenResult.get('missionDialog').dataset.outcome,'lost');assert.equal(hiddenResult.soundEvents.some(([name,kind])=>name==='play'&&kind==='lost'),false,'A delayed result does not make sound in a hidden tab');
console.log('PASS: arrival locks cards without consuming time, can be skipped, pauses on background, and result scenes/sounds synchronize once with safe restart cancellation.');
const settingsUI=boot();settingsUI.get('memoryTimeSettings').click();assert.equal(settingsUI.get('timeSettingsDialog').open,true);assert.equal(settingsUI.get('memoryTimeSettings').getAttribute('aria-expanded'),'true');assert.equal(settingsUI.document.activeElement,settingsUI.get('timeSettingsTitle'));settingsUI.get('timePlus').click();assert.equal(settingsUI.get('setupTime').textContent,'04:00');settingsUI.get('memoryThemeSettings').click();assert.equal(settingsUI.get('themeSettingsDialog').open,false,'Settings dialogs never stack');settingsUI.get('memoryStart').click();assert.equal(settingsUI.get('memoryGrid').children.length,0,'A settings dialog must close before launching');settingsUI.step(30000);assert.equal(settingsUI.get('setupTime').textContent,'04:00');assert.equal(settingsUI.soundEvents.length,0,'Home settings do not activate game audio');settingsUI.get('timeSettingsDone').click();assert.equal(settingsUI.get('timeSettingsDialog').open,false);assert.equal(settingsUI.get('memoryTimeSettings').getAttribute('aria-expanded'),'false');assert.equal(settingsUI.document.activeElement,settingsUI.get('memoryTimeSettings'));
settingsUI.get('memoryThemeSettings').click();settingsUI.get('memoryThemes').children[1].click();assert.equal(settingsUI.get('currentTheme').textContent,'B');assert.match(settingsUI.get('memoryThemeSettings').getAttribute('aria-label'),/B 水晶能源/);assert.match(settingsUI.get('themeSelection').textContent,/B 水晶能源/);settingsUI.get('themeSettingsDialog')['event-cancel']({preventDefault(){}});assert.equal(settingsUI.get('themeSettingsDialog').open,false);assert.equal(settingsUI.document.activeElement,settingsUI.get('memoryThemeSettings'));assert.equal(boot({storage:settingsUI.storage}).get('currentTheme').textContent,'B','Chosen theme remains saved after closing with Escape');settingsUI.get('memoryThemeSettings').click();settingsUI.get('themeSettingsDone').click();assert.equal(settingsUI.get('themeSettingsDialog').open,false);
for(const [trigger,panel,close] of [['memoryTimeSettings','timeSettingsDialog','timeSettingsClose'],['memoryThemeSettings','themeSettingsDialog','themeSettingsClose']]){settingsUI.get(trigger).click();settingsUI.get(close).click();assert.equal(settingsUI.get(panel).open,false);settingsUI.get(trigger).click();const dialog=settingsUI.get(panel);dialog['event-click']({target:dialog,clientX:50,clientY:50});assert.equal(dialog.open,true,'Clicking panel padding does not close it');dialog['event-click']({target:dialog,clientX:-1,clientY:50});assert.equal(dialog.open,false,'Clicking the backdrop closes settings');assert.equal(settingsUI.document.activeElement,settingsUI.get(trigger));}
settingsUI.get('memoryStart').click();assert.equal(settingsUI.get('timeValue').textContent,'04:00');settingsUI.get('memoryTimeSettings').click();assert.equal(settingsUI.get('timeSettingsDialog').open,false,'Home settings cannot change an active mission');
const settingsMarkup=fs.readFileSync('memory.html','utf8'),homeMarkup=settingsMarkup.match(/<section id="memoryHome"[\s\S]*?<\/section>/)[0];assert.doesNotMatch(homeMarkup,/id="(?:memoryThemes|timeMinus|timePlus)"/,'Only setting launchers appear on the home screen');for(const [panel,control] of [['timeSettingsDialog','timePlus'],['themeSettingsDialog','memoryThemes']]){const modal=settingsMarkup.match(new RegExp('<dialog id="'+panel+'"[\\s\\S]*?<\\/dialog>'))[0];assert.ok(modal.includes('id="'+control+'"'));assert.ok(modal.includes('aria-labelledby='));}
console.log('PASS: image buttons open separate settings dialogs, selections update home summaries, all closing paths restore focus, and dialogs cannot launch or alter a running game.');
// Scoring depends on the pairing sequence, independently of the chosen clock.
const scores=[];
for(const seconds of [180,600,null]){let game=E.create(16,()=>.42,0,seconds),now=0;for(const symbol of new Set(game.deck)){for(let i=0;i<game.size;i++)if(game.deck[i]===symbol)game=E.act(game,{type:'flip',index:i},now).state;now+=650;game=E.act(game,{type:'tick'},now).state;}scores.push(game.score);assert.equal(game.bonus,(seconds===null?0:Math.floor(game.remainingMs/1000)*2)+game.shields*10);}
assert.deepEqual(scores,[1500,1500,1500]);

const savedUI=boot();savedUI.get('memoryCounts').children[4].click();savedUI.get('timePlus').click();savedUI.get('timePlus').click();
for(const id of ['memoryMusic','memorySound']){savedUI.get(id).checked=false;savedUI.get(id).onchange();}
const restored=boot({storage:savedUI.storage});assert.equal(restored.get('setupTime').textContent,'07:30');assert.equal(restored.get('memoryCounts').children[4].getAttribute('aria-pressed'),'true');assert.equal(restored.get('memoryMusic').checked,false);assert.equal(restored.get('memorySound').checked,false);assert.equal(restored.soundEvents.length,0);restored.get('memoryStart').click();assert.equal(restored.get('timeValue').textContent,'07:30');assert.ok(restored.soundEvents.some(([kind,enabled])=>kind==='music'&&enabled===false));
for(let i=0;i<4;i++)savedUI.get('timePlus').click();assert.equal(boot({storage:savedUI.storage}).get('setupTime').textContent,'∞');

const deferred=boot();assert.equal(deferred.imageRequests.length,4);assert.ok(deferred.imageRequests.every(img=>!img.url.includes('result-')));
for(const id of ['resultWinArt','resultLossArt']){const imgTag=settingsMarkup.match(new RegExp('<img id="'+id+'"[^>]*>'))[0];assert.match(imgTag,/ data-src="[^\"]+\.webp"/);assert.doesNotMatch(imgTag,/\ssrc=/);}
deferred.get('memoryStart').click();assert.equal(deferred.imageRequests.length,6);assert.ok(deferred.get('resultWinArt').classList.contains('is-ready'));deferred.get('memoryRestart').click();deferred.get('dialogRestart').click();assert.equal(deferred.imageRequests.length,6,'Result artwork is prepared after launch and reused across retries');
const failedScene=boot({imagesPending:true});failedScene.settleImages();failedScene.get('memoryStart').click();failedScene.settleImages(false);failedScene.get('memoryGrid').children[0].click();assert.equal(failedScene.get('flipsValue').textContent,'1','Optional ending artwork failure never blocks gameplay');assert.equal(failedScene.get('resultWinArt').src,'');

function gridDimensions(app){const style=app.get('memoryGrid').style,cols=Number(style['--cols']),gap=parseFloat(style['--gap']),width=parseFloat(style['--grid-width']),tileH=parseFloat(style['--card-height']),rows=Math.ceil(app.get('memoryGrid').children.length/cols);return {cols,width,height:rows*tileH+gap*(rows-1),tileW:tileH/1.25};}
assert.match(settingsMarkup,/<div id="memoryBoard" class="memory-board"><div id="memoryGrid"/,'The measured board area must wrap the actual card grid');
const screens=[{width:320,height:568,boardWidth:300,boardHeight:350},{width:360,height:640,boardWidth:340,boardHeight:414},{width:390,height:844,boardWidth:370,boardHeight:610},{width:430,height:932,boardWidth:410,boardHeight:684},{width:568,height:320,boardWidth:528,boardHeight:174},{width:667,height:375,boardWidth:627,boardHeight:229},{width:844,height:390,boardWidth:756,boardHeight:240},{width:932,height:430,boardWidth:844,boardHeight:280},{width:768,height:1024,boardWidth:748,boardHeight:790},{width:1024,height:768,boardWidth:1004,boardHeight:534}];
for(const screen of screens)for(const count of E.COUNTS){
 const app=boot(screen);app.get('memoryCounts').children.find(button=>Number(button.dataset.count)===count).click();
 const shown=Number(app.get('setupCards').textContent),time=app.get('setupTime').textContent;
 assert.ok(shown>=count&&shown<=count+E.EXTRA[count]);assert.equal(shown%2,0);
 assert.equal(app.get('setupPairs').textContent,String(shown/2).padStart(2,'0'));
 app.get('memoryStart').click();const grid=gridDimensions(app);
 assert.equal(app.document.body.classList.contains('fit-board'),true);assert.equal(app.get('memoryGrid').children.length,shown);assert.equal(app.get('timeValue').textContent,time);assert.equal(shown%grid.cols,0,'No empty cells in the rectangle');
 assert.ok(grid.width<=screen.boardWidth-12+.01);assert.ok(grid.height<=screen.boardHeight-12+.01);assert.ok(grid.tileW>0);assert.equal(app.get('memoryBoardHint').hidden,true);
 if(screen.width<=600&&screen.width<screen.height){assert.equal(grid.cols,E.PHONE_COLUMNS[count]);assert.equal(shown,Math.ceil(count/E.PHONE_COLUMNS[count])*E.PHONE_COLUMNS[count]);}else for(let candidateCount=count;candidateCount<=count+E.EXTRA[count];candidateCount+=2)for(let cols=1;cols<=candidateCount;cols++){if(candidateCount%cols)continue;const rows=candidateCount/cols,candidate=Math.min(128,(screen.boardWidth-12-4*(cols-1))/cols,(screen.boardHeight-12-4*(rows-1))/rows/1.25);assert.ok(grid.tileW+.021>=candidate,'Choose the largest cards among bounded complete rectangles');}
}
const rotated=boot(screens[2]);rotated.get('memoryCounts').children[4].click();rotated.get('memoryStart').click();const identity=rotated.get('memoryGrid').children,portrait=gridDimensions(rotated);identity[0].click();rotated.visualResize(724,490);const shorter=gridDimensions(rotated);assert.equal(shorter.cols,portrait.cols,'Browser address bars do not move remembered columns');assert.ok(shorter.height<=478);assert.equal(rotated.document.body.style['--mission-viewport'],'724px');rotated.visualResize(362,245,2);assert.deepEqual(gridDimensions(rotated),shorter,'Pinch zoom magnifies without rearranging cards');rotated.visualResize(724,490);rotated.resize(844,390,756,240);assert.notEqual(gridDimensions(rotated).cols,portrait.cols);assert.ok(gridDimensions(rotated).height<=228);assert.equal(rotated.get('memoryGrid').children,identity,'Rotation never rebuilds or reshuffles the deck');assert.equal(identity[0].classList.contains('flipped'),true);assert.equal(rotated.get('flipsValue').textContent,'1');rotated.resize(390,844,370,610);assert.equal(gridDimensions(rotated).cols,portrait.cols);rotated.get('memoryPause').click();rotated.resize(844,390,756,240);assert.equal(rotated.get('memoryGrid').classList.contains('obscured'),true,'Resizing a paused game keeps its cards covered');rotated.get('dialogMenu').click();assert.equal(rotated.document.body.classList.contains('fit-board'),false,'Returning home restores normal page scrolling');
const desktop=boot({width:1440,height:900});desktop.get('memoryCounts').children[4].click();desktop.get('memoryStart').click();assert.equal(desktop.document.body.classList.contains('fit-board'),false);assert.equal(gridDimensions(desktop).cols,12);assert.ok(gridDimensions(desktop).tileW>=80);
console.log('PASS: all five deck sizes fit both dimensions of 10 portrait/landscape board areas; address-bar changes, pinch zoom, rotation, pause and menu preserve the mission.');
// Regression: tall phones previously alternated between 32 (4x8) and 36 (6x6).
for(const [height,boardHeight] of [[724,490],[844,610],[932,698]]){
 const phone=boot({width:390,height,boardWidth:370,boardHeight});phone.get('memoryCounts').children[2].click();
 const summary=()=>[phone.get('setupCards').textContent,phone.get('setupLayout').textContent,phone.get('setupShield').textContent,phone.get('setupTime').textContent];
 assert.deepEqual(summary(),['36','6 × 6','54','04:30']);
 phone.visualResize(724,490);assert.deepEqual(summary(),['36','6 × 6','54','04:30']);
 phone.resize(390,932,370,698);assert.deepEqual(summary(),['36','6 × 6','54','04:30']);
 phone.get('memoryStart').click();const cards=phone.get('memoryGrid').children;assert.equal(cards.length,36);assert.equal(gridDimensions(phone).cols,6);assert.equal(phone.get('pairsValue').textContent,'0/18');
 cards[0].click();phone.visualResize(724,490);assert.equal(gridDimensions(phone).cols,6);assert.ok(gridDimensions(phone).height<=478);assert.equal(phone.get('memoryGrid').children,cards);assert.equal(cards[0].classList.contains('flipped'),true);
 phone.get('memoryRestart').click();phone.get('dialogRestart').click();assert.equal(phone.get('memoryGrid').children.length,36);assert.equal(gridDimensions(phone).cols,6);
 phone.get('memoryPause').click();phone.get('dialogMenu').click();assert.deepEqual(summary(),['36','6 × 6','54','04:30']);
}

const idle=boot({canvas:true});idle.get('memoryStart').click();const scoreWrites=idle.get('scoreValue').textWrites,timeWrites=idle.get('timeValue').textWrites;for(let i=0;i<180;i++)idle.step(1000/60);assert.equal(idle.frames.size,0);assert.equal(idle.canvasCalls.length,0,'An idle board does not clear or redraw the canvas');assert.equal(idle.get('scoreValue').textWrites,scoreWrites);assert.ok(idle.get('timeValue').textWrites-timeWrites<=3,'Only changed countdown seconds update the HUD');idle.get('memoryPause').click();assert.equal(idle.timers.size,0,'Pause cancels the gameplay timer');
const freeIdle=boot({storage:new Map([[R.PREFS_KEY,JSON.stringify({size:16,duration:null})]])});freeIdle.get('memoryStart').click();assert.equal(freeIdle.timers.size,0);assert.equal(freeIdle.frames.size,0,'Unlimited thinking time needs neither polling nor animation frames');const wrongIndex=deck.findIndex(symbol=>symbol!==deck[0]);freeIdle.get('memoryGrid').children[0].click();freeIdle.get('memoryGrid').children[wrongIndex].click();freeIdle.step(1099);assert.equal(freeIdle.get('shieldValue').textContent,'16/16');freeIdle.step(1);assert.equal(freeIdle.get('shieldValue').textContent,'15/16');assert.equal(freeIdle.timers.size,0,'Mismatch resolution still happens on time in unlimited mode');
const sparks=boot({canvas:true,reduced:false});sparks.get('memoryStart').click();sparks.get('launchSkip').click();for(let i=0;i<deck.length;i++)if(deck[i]===deck[0])sparks.get('memoryGrid').children[i].click();for(let i=0;i<10;i++)sparks.step(100);assert.ok(sparks.canvasCalls.includes('draw'));assert.equal(sparks.frames.size,0);const clears=sparks.canvasCalls.length;sparks.step(1000);assert.equal(sparks.canvasCalls.length,clears,'Finished particles stop requesting frames and leave no trails');

const progress=boot();progress.get('memoryStart').click();progress.get('memoryGrid').children[0].click();progress.get('memoryGrid').children[wrongIndex].click();progress.step(1100);solveUI(progress);assert.match(progress.get('progressTitle').textContent,/第一份/);assert.equal(progress.get('resultProgress').hidden,false);assert.ok(progress.get('dialogStats').textContent.includes('配對命中率89%'));const countRuns=()=>JSON.parse(progress.storage.get(R.HISTORY_KEY)).length;assert.equal(countRuns(),1);progress.step(10000);assert.equal(countRuns(),1,'A result is recorded once even if the dialog stays open');progress.get('dialogRestart').click();solveUI(progress);assert.match(progress.get('progressTitle').textContent,/少翻 2 次/);assert.ok(progress.get('dialogStats').textContent.includes('配對得分1,500'));assert.match(progress.get('survivalCopy').textContent,/獨立於配對得分/);assert.equal(countRuns(),2);progress.get('memoryHelp').click();assert.equal(progress.get('resultProgress').hidden,true);assert.equal(progress.get('survivalReward').hidden,true);
console.log('PASS: optimized memory UI keeps scores independent of time, restores settings, defers ending images, fits mobile deck layouts, avoids idle redraws, and reports comparable progress once per mission.');
// Every allowed padded size must still contain exactly two of each symbol and finish correctly.
for(const base of E.COUNTS)for(let size=base;size<=base+E.EXTRA[base];size+=2){
 let game=E.create(size,()=>.42,0,null),now=0,expectedScore=0;const symbols=new Set(game.deck);
 assert.equal(game.size,size);assert.equal(symbols.size,size/2);assert.ok([...symbols].every(id=>game.deck.filter(value=>value===id).length===2));
 assert.equal(game.initialShields,Math.ceil(E.SHIELDS[base]*size/base));assert.equal(E.rules(size).seconds,Math.ceil(E.SECONDS[base]*size/base/30)*30);
 for(const [combo,symbol] of [...symbols].entries()){for(let index=0;index<size;index++)if(game.deck[index]===symbol)game=E.act(game,{type:'flip',index},now).state;expectedScore+=100+Math.min(9,combo)*25;assert.equal(game.phase,combo===size/2-1?'won':'resolving');now+=650;game=E.act(game,{type:'tick'},now).state;}
 assert.equal(game.score,expectedScore);assert.equal(game.bonus,game.initialShields*10);
}
assert.equal(bySymbol.size,30,'The maximum deck renders all 30 unique equipment images');
const padded=boot({width:390,height:800,boardWidth:370,boardHeight:530});padded.get('memoryCounts').children[3].click();
assert.equal(padded.get('setupCards').textContent,'42','A six-column phone layout fills the last two cells');assert.equal(padded.get('setupLayout').textContent,'6 × 7');assert.equal(padded.get('setupShield').textContent,'76');assert.equal(padded.get('setupPairs').textContent,'21');
const recommended=padded.get('setupTime').textContent;padded.get('timePlus').click();const customTime=padded.get('setupTime').textContent;assert.notEqual(customTime,recommended);
padded.resize(1440,900);assert.equal(padded.get('setupTime').textContent,customTime,'Manual time survives a new home layout');
padded.resize(390,800,370,530);padded.get('memoryStart').click();const paddedCards=padded.get('memoryGrid').children;assert.equal(paddedCards.length,42);padded.resize(1440,900);assert.equal(padded.get('memoryGrid').children,paddedCards);assert.equal(42%gridDimensions(padded).cols,0);
padded.get('memoryRestart').click();padded.get('dialogRestart').click();assert.equal(padded.get('memoryGrid').children.length,42,'Retry freezes the original actual count even after rotation');assert.equal(padded.get('timeValue').textContent,customTime);
const restoredPadded=boot({storage:padded.storage,width:390,height:800,boardWidth:370,boardHeight:530});assert.equal(restoredPadded.get('setupTime').textContent,customTime);
const autoPlan=boot();autoPlan.get('memoryCounts').children[4].click();autoPlan.resize(1440,900);assert.equal(autoPlan.get('setupCards').textContent,'60');assert.equal(autoPlan.get('setupTime').textContent,'06:00');
autoPlan.get('timePlus').click();autoPlan.get('timeMinus').click();autoPlan.resize(390,844);assert.equal(autoPlan.get('setupTime').textContent,'06:00','Manually returning to the recommendation still counts as a custom time');
const freePlan=boot({storage:new Map([[R.PREFS_KEY,JSON.stringify({size:52,duration:null})]])});freePlan.resize(1440,900);assert.equal(freePlan.get('setupTime').textContent,'∞');
assert.equal(padded.document.body.classList.contains('measuring-mission'),false);assert.equal(autoPlan.document.body.classList.contains('in-mission'),false);
console.log('PASS: bounded + levels fill rectangles, preview real settings, keep exact unique pairs and scoring, preserve manual/unlimited time, and freeze retry decks.');
require('./test-memory-records.cjs');
require('./test-memory-audio.cjs');
