const soundNotes=[];let audioCreates=0;class MockAudio{constructor(){audioCreates++;this.state='running';this.currentTime=0;this.destination={};}createOscillator(){const note={hz:0,stopped:false};return {frequency:{setValueAtTime(hz){note.hz=hz;}},connect(){},disconnect(){},start(time){note.start=time;soundNotes.push(note);},stop(){note.stopped=true;}};}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}}
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),m={exports:{}};
vm.runInNewContext(fs.readFileSync('assets/abacus-engine.js','utf8'),{module:m});const E=m.exports;
for(let col=0;col<5;col++)for(let digit=0;digit<10;digit++){const s=E.create();if(digit>=5)E.move(s,col,0);if(digit%5)E.move(s,col,digit%5);assert.equal(E.value(s),digit*10**(4-col));assert.equal(s.result,null);}
const s=E.create();assert.equal(E.check(s),null);E.setProblem(s,'12','+','7');E.move(s,4,4);assert.equal(s.result,null);assert.equal(E.check(s),false);E.move(s,3,1);E.move(s,4,0);assert.equal(E.value(s),19);assert.equal(s.result,null);assert.equal(E.check(s),true);E.clear(s);assert.equal(E.value(s),0);assert.equal(s.problem.answer,19);assert.equal(s.result,null);
for(const args of [['','',''],['1.2','+','3'],['-1','+','4'],['1e2','+','1'],['1','-','2'],['99999','+','1'],['1','*','2']])assert.throws(()=>E.setProblem(s,...args));
E.setProblem(s,'99999','-','99999');assert.equal(E.check(s),true);E.setProblem(s,'99999','+','0');s.digits.fill(9);assert.equal(E.check(s),true);E.free(s);assert.equal(E.value(s),99999);assert.equal(E.check(s),null);
const nodes=new Map();function el(){return {textContent:'',checked:false,value:'',disabled:false,style:{},dataset:{},attrs:{},events:{},children:[],setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,f){this.events[k]=f;},append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;this.textContent=items.map(item=>item.textContent).join('');}};}function node(id){if(!nodes.has(id))nodes.set(id,el());return nodes.get(id);}
node('first').value='12';node('second').value='7';const effectTimers=new Map();let effectTimerId=0;const document={getElementById:node,createElement:el};vm.runInNewContext(fs.readFileSync('assets/abacus-ui.js','utf8'),{window:{AbacusPractice:E,AudioContext:MockAudio},document,setTimeout(fn){effectTimers.set(++effectTimerId,fn);return effectTimerId;},clearTimeout(id){effectTimers.delete(id);}});
const click=id=>node(id).events.click(),submit=()=>node('problemForm').events.submit({preventDefault(){}});
assert.equal(audioCreates,0);assert.equal(node('field').children.length,5);assert.equal(node('check').disabled,true);submit();assert.equal(node('check').disabled,false);assert.equal(node('value').textContent,'0');
const bead=(col,i)=>node('field').children[col].children[i].events.click();
bead(3,1);bead(4,4);bead(4,0);assert.equal(node('value').textContent,'19');assert.notEqual(node('feedback').dataset.kind,'success');click('check');assert.equal(node('feedback').dataset.kind,'success');bead(4,0);assert.equal(node('feedback').dataset.kind,'');click('check');assert.equal(node('feedback').dataset.kind,'retry');bead(4,0);click('check');assert.equal(node('feedback').dataset.kind,'success');
click('clear');assert.equal(node('value').textContent,'0');assert(node('question').textContent.includes('12'));node('first').value='3';node('first').events.input();assert.equal(node('check').disabled,true);node('subtract').checked=true;submit();assert(node('formError').textContent);assert.equal(node('check').disabled,true);node('second').value='2';submit();assert.equal(node('check').disabled,false);bead(4,1);click('check');assert.equal(node('feedback').dataset.kind,'success');click('free');assert.equal(node('check').disabled,true);assert.equal(node('value').textContent,'1');
console.log('PASS: all digits/places, explicit-only checking, unlimited retry, clear retains problem, free practice, input validation and real UI controls.');
node('problemDialog').showModal=function(){this.open=true;};node('problemDialog').close=function(){this.open=false;this.events.close();};node('openProblem').focus=()=>{};
click('openProblem');assert.equal(node('problemDialog').open,true);node('first').value='9';node('first').events.input();click('closeProblem');assert.equal(node('first').value,'3');assert.equal(node('problemDialog').open,false);assert.equal(node('value').textContent,'1');
click('openProblem');submit();assert.equal(node('problemDialog').open,false);assert.equal(node('check').disabled,false);click('openProblem');node('first').value='-1';submit();assert.equal(node('problemDialog').open,true);click('closeProblem');assert.equal(node('check').disabled,false);click('openProblem');click('free');assert.equal(node('problemDialog').open,false);
console.log('PASS: question dialog opens, cancels drafts without losing beads, stays open on invalid input, and closes on valid question or free practice.');
for(const limit of [10,20,100,1000,99999])for(const op of ['+','-','mixed']){const r=E.create();let previous='';for(let i=0;i<500;i++){E.randomProblem(r,limit,op);const p=r.problem;assert(p.a>=1&&p.a<=limit&&p.b>=1&&p.b<=limit&&p.answer>=1&&p.answer<=limit);if(op!=='mixed')assert.equal(p.op,op);assert.notEqual(JSON.stringify(p),previous);previous=JSON.stringify(p);assert.equal(E.value(r),0);assert.equal(r.result,null);}}
for(const edge of [0,.5,.999999999])for(const op of ['+','-','mixed']){const r=E.create();E.randomProblem(r,10,op,()=>edge);const before=JSON.stringify(r.problem);E.randomProblem(r,10,op,()=>edge);assert.notEqual(JSON.stringify(r.problem),before);assert(r.problem.answer>=1&&r.problem.answer<=10);}
click('computerSource');assert.equal(node('problemForm').hidden,true);assert.equal(node('computerForm').hidden,false);node('autoLimit').value='10';node('autoOperation').value='+';click('openProblem');node('computerForm').events.submit({preventDefault(){}});assert.equal(node('problemDialog').open,false);assert.equal(node('questionLabel').textContent,'電腦出題 · 第 1／5 題');assert.equal(node('check').textContent,'確認答案');
const questionBefore=node('question').textContent,nums=questionBefore.match(/\d+/g).map(Number),answer=nums[0]+nums[1];
click('clear');for(let c=0;c<5;c++){const d=Number(String(answer).padStart(5,'0')[c]);if(d>=5)bead(c,0);if(d%5)bead(c,d%5);}assert.equal(node('check').textContent,'確認答案');click('check');assert.equal(node('check').textContent,'下一題');assert.equal(node('question').textContent,questionBefore);click('check');assert.notEqual(node('question').textContent,questionBefore);assert.equal(node('value').textContent,'0');assert.equal(node('check').textContent,'確認答案');click('free');assert.equal(node('check').disabled,true);click('manualSource');assert.equal(node('problemForm').hidden,false);
console.log('PASS: 7,500 random problems respect bounds/operations, do not repeat consecutively, and require explicit confirmation before next question.');
node('first').value='2';node('second').value='1';node('subtract').checked=true;submit();click('check');assert.equal(node('answerEffect').hidden,false);assert.equal(node('answerEffect').dataset.kind,'retry');assert.equal(effectTimers.size,1);click('check');assert.equal(effectTimers.size,1);bead(4,1);assert.equal(node('answerEffect').hidden,true);assert.equal(effectTimers.size,0);click('check');assert.equal(node('answerEffect').dataset.kind,'success');assert.equal(node('effectLabel').textContent,'答對了！');for(const fn of [...effectTimers.values()])fn();assert.equal(node('answerEffect').hidden,true);assert.equal(effectTimers.size,0);click('check');click('openProblem');assert.equal(node('answerEffect').hidden,true);click('closeProblem');
console.log('PASS: correct/wrong effects appear only on confirmation, replace repeated effects, auto-dismiss, and clear on editing or opening settings.');
soundNotes.length=0;click('check');assert.deepEqual(soundNotes.map(n=>n.hz),[880,659.25,880,659.25]);assert.equal(audioCreates,1);click('soundToggle');assert.equal(node('soundToggle').attrs['aria-pressed'],'false');soundNotes.length=0;click('check');assert.equal(soundNotes.length,0);click('soundToggle');click('clear');click('check');assert.deepEqual(soundNotes.map(n=>n.hz),[220,165]);click('clear');assert.equal(effectTimers.size,0);
console.log('PASS: audio starts on answer confirmation only, uses four correct/two wrong notes, reuses one context, and respects mute.');
for(const limit of [10,20,100,1000,99999])for(const op of ['+','-','mixed'])for(const edge of [0,.5,.999999999]){const r=E.create();let previous='';for(let i=0;i<20;i++){E.randomProblem(r,limit,op,()=>edge);const p=r.problem;assert(p.a>0&&p.b>0&&p.a<=limit&&p.b<=limit&&p.answer>0&&p.answer<=limit);assert.notEqual(JSON.stringify(p),previous);previous=JSON.stringify(p);}}
const manual=E.create();E.setProblem(manual,5,'+',0);assert.equal(manual.problem.answer,5);E.setProblem(manual,5,'-',0);assert.equal(manual.problem.answer,5);
console.log('PASS: all computer ranges/operations exclude zero operands, including repeated RNG endpoints; legacy two-number helper remains compatible.');
// Exercise the actual file-backed playback path, including rejected and stale play promises.
for(const count of [2,3,4,5])for(const limit of [10,20,100,1000,99999])for(const op of ['+','-','mixed'])for(const rng of [()=>0,()=>.999999999,Math.random]){const r=E.create();let previous='';for(let i=0;i<100;i++){E.randomSequence(r,limit,op,count,rng);const p=r.problem,terms=p.terms||[p.a,p.b],ops=p.ops||[p.op];assert.equal(terms.length,count);assert.equal(ops.length,count-1);let value=terms[0];terms.forEach(n=>assert(n>0&&n<=limit));ops.forEach((sign,j)=>{if(op!=='mixed')assert.equal(sign,op);value+=sign==='+'?terms[j+1]:-terms[j+1];assert(value>0&&value<=limit);});assert.equal(value,p.answer);const sig=JSON.stringify([terms,ops]);assert.notEqual(sig,previous);previous=sig;}}
const multi=E.create();E.setSequence(multi,[12,7,5,8,3],['+','-','+','-']);assert.equal(multi.problem.answer,19);const intact=JSON.stringify(multi);assert.throws(()=>E.setSequence(multi,[1,2,3],['-','+']));assert.equal(JSON.stringify(multi),intact);assert.throws(()=>E.setSequence(multi,[99999,1,1],['+','-']));assert.throws(()=>E.randomSequence(multi,10,'+',6));
node('subtract').checked=false;node('manualCount').value='5';node('manualCount').events.input();assert.equal(node('termRow5').hidden,false);node('first').value='12';node('second').value='7';node('term3').value='5';node('term4').value='8';node('term5').value='3';node('op3').value='-';node('op4').value='+';node('op5').value='-';submit();assert.equal(node('question').textContent,'12 ＋ 7 − 5 ＋ 8 − 3 ＝ ?');bead(3,1);bead(4,0);bead(4,4);click('check');assert.equal(node('feedback').dataset.kind,'success');click('openProblem');node('manualCount').value='2';node('manualCount').events.input();click('closeProblem');assert.equal(node('manualCount').value,'5');assert.equal(node('termRow5').hidden,false);
node('autoCount').value='5';node('autoLimit').value='10';node('autoOperation').value='mixed';node('computerForm').events.submit({preventDefault(){}});assert.equal(node('question').textContent.match(/\d+/g).length,5);click('free');
console.log('PASS: 18,000 multi-term problems preserve all intermediate bounds, positive operands, operation modes and non-repetition; manual five-term judging and draft restoration work.');
const keypad=node('problemDialog').children.find(child=>child.className==='number-keypad');keypad.showModal=function(){this.open=true;};keypad.close=function(){this.open=false;};
const pressNumber=label=>keypad.children[2].children.find(button=>button.textContent===label).events.click();
click('manualSource');click('openProblem');node('manualCount').value='5';node('manualCount').events.input();const savedFirst=node('first').value;
click('first');assert.equal(keypad.open,true);assert.equal(node('first').readOnly,true);assert.equal(node('first').attrs.inputmode,'none');pressNumber('4');pressNumber('2');assert.equal(node('first').value,'42');pressNumber('⌫');assert.equal(node('first').value,'4');pressNumber('清除');pressNumber('0');pressNumber('7');assert.equal(node('first').value,'7');for(let i=0;i<7;i++)pressNumber('8');assert.equal(node('first').value.length,5);pressNumber('下一個');pressNumber('3');assert.equal(node('second').value,'3');pressNumber('下一個');pressNumber('4');assert.equal(node('term3').value,'4');pressNumber('下一個');pressNumber('5');assert.equal(node('term4').value,'5');pressNumber('下一個');pressNumber('6');assert.equal(node('term5').value,'6');keypad.children.find(child=>child.className==='keypad-back').events.click();assert.equal(keypad.open,false);click('closeProblem');assert.equal(node('first').value,savedFirst);
console.log('PASS: touch keypad replaces values, deletes/clears, limits to five digits, edits every term, closes and preserves cancel-draft restoration.');
// Hold both contacts at once in the same column; each down must act independently.
for(let lower=1;lower<=4;lower++)for(const upperFirst of [true,false]){click('clear');const upper=node('field').children[4].children[0],bottom=node('field').children[4].children[lower];const down=(button,id)=>button.events.pointerdown({pointerId:id,pointerType:'touch',isPrimary:id===1,preventDefault(){}});if(upperFirst){down(upper,1);down(bottom,2);}else{down(bottom,2);down(upper,1);}assert.equal(node('value').textContent,String(5+lower));upper.events.pointerup?.({pointerId:1});bottom.events.pointercancel?.({pointerId:2});upper.events.click({detail:1,pointerType:'touch'});bottom.events.click({detail:1,pointerType:'touch'});assert.equal(node('value').textContent,String(5+lower));down(upper,3);assert.equal(node('value').textContent,String(lower));upper.events.lostpointercapture?.({pointerId:3});upper.events.click({detail:0});assert.equal(node('value').textContent,String(5+lower));}
click('openProblem');node('manualCount').value='3';node('first').value='12';node('second').value='7';node('term3').value='2';node('subtract').checked=false;node('op3').value='+';node('manualCount').events.input();assert.equal(node('manualPreview').textContent,'12 ＋ 7 ＋ 2 ＝ ?');node('signGroup3').children[1].events.click();assert.equal(node('manualPreview').textContent,'12 ＋ 7 − 2 ＝ ?');node('term3').value='99';node('term3').events.input();assert.equal(node('term3').attrs['aria-invalid'],'false');assert.equal(node('formError').textContent,'');click('term3');pressNumber('4');pressNumber('上一個');assert(keypad.children[0].textContent.includes('第 2 口'));keypad.children[3].children[1].events.click();assert.equal(node('subtract').checked,true);assert.equal(node('manualPreview').textContent,'12 − 7 − 4 ＝ ?');keypad.children.find(child=>child.className==='keypad-back').events.click();click('closeProblem');
console.log('PASS: simultaneous same-column upper/lower touches produce 6–9 in both orders, suppress ghost clicks, recover cancellation, preserve keyboard; unified signs, live validation and keypad navigation work.');
click('openProblem');click('second');const keyPreview=keypad.children.find(child=>child.className==='keypad-preview');assert.equal(keyPreview.textContent,node('manualPreview').textContent);assert.equal(keyPreview.children.filter(child=>child.attrs['aria-current']==='true').length,1);assert.equal(keyPreview.children[2].attrs['aria-current'],'true');pressNumber('8');assert.equal(keyPreview.children[2].textContent,'8');assert.equal(keyPreview.textContent,node('manualPreview').textContent);assert(keyPreview.textContent.endsWith('＝ ?'));keypad.children[3].children[0].events.click();assert.equal(keyPreview.textContent,node('manualPreview').textContent);pressNumber('清除');assert(keyPreview.textContent.includes('□'));pressNumber('上一個');assert.equal(keyPreview.children[0].attrs['aria-current'],'true');assert.equal(keyPreview.children[2].attrs['aria-current'],undefined);assert.equal(keyPreview.textContent,node('manualPreview').textContent);keypad.children.find(child=>child.className==='keypad-back').events.click();click('closeProblem');console.log('PASS: keypad shows live full question preview on open, number entry, operator change, clearing and term navigation without revealing the answer.');
// Reject nonpositive manual answers atomically, only when submitting the draft.
const positive=E.create();E.setSequence(positive,[8,2],['+']);E.move(positive,4,2);const beforeInvalid=JSON.stringify(positive);
for(const [terms,ops] of [[[5,5],['-']],[[2,3],['-']],[[0,0],['+']],[[9,3,2,4],['-','-','-']]]){assert.throws(()=>E.setSequence(positive,terms,ops));assert.equal(JSON.stringify(positive),beforeInvalid);}
E.setSequence(positive,[5,5,1],['-','+']);assert.equal(positive.problem.answer,1);
click('openProblem');const previousQuestion=node('question').textContent,previousBeads=node('value').textContent;node('manualCount').value='2';node('first').value='5';node('second').value='5';node('subtract').checked=true;node('second').events.input();assert.equal(node('formError').textContent,'');submit();assert.equal(node('problemDialog').open,true);assert(node('formError').textContent.includes('答案必須大於 0'));assert.equal(node('first').value,'5');assert.equal(node('second').value,'5');assert.equal(node('question').textContent,previousQuestion);assert.equal(node('value').textContent,previousBeads);node('second').value='6';submit();assert.equal(node('problemDialog').open,true);assert.equal(node('question').textContent,previousQuestion);node('second').value='4';submit();assert.equal(node('problemDialog').open,false);assert.equal(node('question').textContent,'5 − 4 ＝ ?');
console.log('PASS: manual submit rejects zero/negative answers without losing draft, beads or question; positive correction starts normally and intermediate zero remains allowed.');
for(let count=2;count<=5;count++)for(let zero=0;zero<count;zero++){const terms=Array(count).fill(2);terms[zero]=0;const state=E.create();E.setSequence(state,[5,1],['+']);const saved=JSON.stringify(state);assert.throws(()=>E.setSequence(state,terms,Array(count-1).fill('+')),new RegExp('第 '+(zero+1)+' 口必須大於 0'));assert.equal(JSON.stringify(state),saved);}
click('openProblem');node('manualCount').value='5';node('subtract').checked=false;for(const id of ['first','second','term3','term4','term5'])node(id).value='2';for(const id of ['op3','op4','op5'])node(id).value='+';node('term4').value='0';submit();assert.equal(node('problemDialog').open,true);assert(node('formError').textContent.includes('第 4 口必須大於 0'));assert.equal(node('term4').value,'0');node('term4').value='1';submit();assert.equal(node('problemDialog').open,false);assert.equal(node('question').textContent,'2 ＋ 2 ＋ 2 ＋ 1 ＋ 2 ＝ ?');
console.log('PASS: zero is rejected at every operand position for 2–5 terms; submit preserves zero draft and names the offending term; correction starts practice.');
node('completionDialog').showModal=function(){this.open=true;};node('completionDialog').close=function(){this.open=false;};
const solveCurrent=()=>{const question=node('question').textContent,values=question.match(/\d+/g).map(Number),signs=question.match(/[＋−]/g);let answer=values[0];signs.forEach((sign,i)=>answer+=sign==='＋'?values[i+1]:-values[i+1]);click('clear');String(answer).padStart(5,'0').split('').forEach((n,col)=>{const digit=Number(n);if(digit>=5)bead(col,0);if(digit%5)bead(col,digit%5);});click('check');};
const setManual=(a,b)=>{node('manualCount').value='2';node('first').value=String(a);node('second').value=String(b);node('subtract').checked=false;node('first').events.input();};
click('openProblem');setManual(1,2);click('addQuestion');assert.equal(node('manualQuestionList').children.length,2);assert.equal(node('first').value,'');submit();assert.equal(node('problemDialog').open,true);assert(node('formError').textContent.includes('第 2 題'));setManual(2,3);node('manualQuestionList').children[0].children[0].events.click();assert.equal(node('first').value,'1');node('second').value='0';node('second').events.input();node('manualQuestionList').children[1].children[0].events.click();submit();assert(node('formError').textContent.includes('第 1 題'));assert(node('formError').textContent.includes('第 2 口'));node('second').value='2';node('second').events.input();submit();assert.equal(node('questionLabel').textContent,'自己出題 · 第 1／2 題');click('check');assert.equal(node('feedback').dataset.kind,'retry');assert.equal(node('questionLabel').textContent,'自己出題 · 第 1／2 題');solveCurrent();assert.equal(node('check').textContent,'下一題');const solvedValue=node('value').textContent;bead(4,1);click('clear');assert.equal(node('value').textContent,solvedValue);
click('openProblem');click('addQuestion');setManual(9,1);node('manualQuestionList').children[0].children[1].events.click();click('closeProblem');assert.equal(node('manualQuestionList').children.length,2);assert.equal(node('check').textContent,'下一題');click('check');assert.equal(node('question').textContent,'2 ＋ 3 ＝ ?');assert.equal(node('value').textContent,'0');solveCurrent();assert.equal(node('completionDialog').open,true);assert.equal(node('completionSummary').textContent,'你完成了 2 題練習！');assert.equal(node('check').disabled,true);click('check');assert.equal(node('questionLabel').textContent,'自己出題 · 第 2／2 題');click('closeCompletion');assert.equal(node('completionDialog').open,false);
for(const total of [5,10,20]){click('openProblem');node('autoTotal').value=String(total);node('autoCount').value='3';node('autoLimit').value='10';node('autoOperation').value='mixed';node('computerForm').events.submit({preventDefault(){}});for(let i=1;i<=total;i++){assert.equal(node('questionLabel').textContent,'電腦出題 · 第 '+i+'／'+total+' 題');solveCurrent();if(i<total){assert.equal(node('completionDialog').open,false);assert.equal(node('check').textContent,'下一題');click('check');assert.equal(node('value').textContent,'0');}}assert.equal(node('completionDialog').open,true);assert.equal(node('completionSummary').textContent,'你完成了 '+total+' 題練習！');click('closeCompletion');}
click('openProblem');node('autoTotal').value='0';const lastQuestion=node('question').textContent;node('computerForm').events.submit({preventDefault(){}});assert.equal(node('question').textContent,lastQuestion);assert(node('autoError').textContent);click('closeProblem');click('free');assert.equal(node('check').disabled,true);
console.log('PASS: manual sets add/edit/remove and cancel safely, validate every question, retry without advancing, lock solved beads, reset on explicit next, finish exactly once; complete 5/10/20 computer sets and reject invalid total.');
// Regression: a missing release on the first lower bead at 11 must not block it at 14.
click('free');click('clear');
let regressionId=0;const touchBead=(col,index,id=++regressionId)=>{const button=node('field').children[col].children[index];button.setPointerCapture=()=>{throw Error('capture unavailable');};button.events.pointerdown({pointerId:id,pointerType:'touch',preventDefault(){}});button.events.click({detail:1,pointerType:'touch'});};
touchBead(3,1);touchBead(4,1);touchBead(4,2);touchBead(4,3);touchBead(4,4);assert.equal(node('value').textContent,'14');touchBead(4,1);assert.equal(node('value').textContent,'10');touchBead(4,1,99);touchBead(4,1,99);assert.equal(node('value').textContent,'10');click('clear');touchBead(4,1);assert.equal(node('value').textContent,'1');
// All contacts intentionally omit pointerup/cancel, including repeated pointer IDs.
for(let round=0;round<3;round++){click('clear');for(let value=1;value<=100;value++){const before=node('value').textContent.padStart(5,'0'),after=String(value).padStart(5,'0');for(let col=0;col<5;col++){const from=Number(before[col]),to=Number(after[col]);if((from>=5)!==(to>=5))touchBead(col,0,1);if(from%5!==to%5)touchBead(col,to%5>from%5?to%5:to%5+1,2);}assert.equal(Number(node('value').textContent),value);}}
const inputBead=node('field').children[4].children[1];click('clear');inputBead.events.pointerdown({pointerType:'pen',pointerId:8,preventDefault(){}});inputBead.events.click({detail:1});assert.equal(node('value').textContent,'1');inputBead.events.pointerdown({pointerType:'mouse'});inputBead.events.click({detail:1});assert.equal(node('value').textContent,'0');inputBead.events.click({detail:0});assert.equal(node('value').textContent,'1');
console.log('PASS: iPad 11→14→10 regression, missing releases, reused pointer IDs, unavailable capture, clear recovery, 3 full 1–100 runs, pen/mouse/keyboard and ghost-click suppression.');
// Revised flow: no premature errors, complete-in-keypad validation and direct continuation.
click('openProblem');click('manualSource');setManual(1,2);click('addQuestion');assert.equal(node('formError').textContent,'');assert.equal(node('first').attrs['aria-invalid'],'false');assert(node('startManual').textContent.includes('3 題'));click('first');pressNumber('完成本題');const readyActions=keypad.children.find(child=>child.className==='keypad-finish-actions'),keyError=keypad.children.find(child=>child.className==='keypad-error');assert(keyError.textContent);assert.equal(readyActions.hidden,true);pressNumber('2');pressNumber('下一個');pressNumber('3');pressNumber('完成本題');assert.equal(readyActions.hidden,false);assert.equal(keypad.children[2].hidden,true);readyActions.children[0].events.click();assert.equal(keypad.children[2].hidden,false);pressNumber('完成本題');readyActions.children[1].events.click();assert.equal(keypad.children[2].hidden,false);assert.equal(node('first').value,'');assert.equal(keyError.textContent,'');assert.equal(node('formError').textContent,'');pressNumber('4');pressNumber('下一個');pressNumber('5');pressNumber('完成本題');readyActions.children[2].events.click();assert.equal(keypad.open,false);assert.equal(node('problemDialog').open,false);assert.equal(node('questionLabel').textContent,'自己出題 · 第 1／4 題');click('free');
console.log('PASS: blank drafts stay neutral; keypad validates completion, offers edit/add/start, enters next blank question directly and starts all four questions.');
(async()=>{nodes.clear();effectTimers.clear();soundNotes.length=0;let player,plays=0,rejectPlay=null;
 class MockClip{constructor(src){this.src=src;player=this;this.paused=true;}pause(){this.paused=true;}play(){plays++;this.paused=false;return new Promise((resolve,reject)=>{rejectPlay=reject;});}}
 node('first').value='12';node('second').value='7';
 vm.runInNewContext(fs.readFileSync('assets/abacus-ui.js','utf8'),{window:{AbacusPractice:E,AudioContext:MockAudio,Audio:MockClip},document,setTimeout(fn){effectTimers.set(++effectTimerId,fn);return effectTimerId;},clearTimeout(id){effectTimers.delete(id);}});
 assert.equal(plays,0);assert.equal(player.volume,.9);assert.equal(player.src,'/assets/abacus-error-kenney-v1.wav');submit();click('check');assert.equal(plays,1);assert.equal(soundNotes.length,0);click('soundToggle');assert.equal(player.paused,true);rejectPlay(Error('cancelled'));await Promise.resolve();assert.equal(soundNotes.length,0);click('check');assert.equal(plays,1);click('soundToggle');click('check');rejectPlay(Error('decode failure'));await Promise.resolve();assert.deepEqual(soundNotes.map(n=>n.hz),[220,165]);click('clear');assert.equal(player.paused,true);
 console.log('PASS: packaged error audio plays only for wrong confirmation, respects mute, and safely falls back without stale playback.');
})().catch(error=>{console.error(error);process.exitCode=1;});
