const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const box={};vm.runInNewContext(fs.readFileSync('assets/blocks-engine.js','utf8'),box);const C=box.CandyBlocks;
let seed=41;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);let g=new C.Game(random);assert.equal(g.board.length,20);assert(g.board.every(r=>r.length===10));assert.equal(g.status,'ready');assert(!g.move(1));assert(!g.hardDrop());assert(g.start());assert(!g.start());
for(let round=0;round<50;round++){g.bag=[];const types=Array.from({length:7},()=>g.draw());assert.equal(new Set(types).size,7,'Each bag contains all seven shapes');}
for(const type of Object.keys(C.SHAPES)){g=new C.Game(random);g.start();g.active={type,cells:C.SHAPES[type].map(p=>p.slice()),x:3,y:5};const original=JSON.stringify(g.active.cells);for(let i=0;i<4;i++)g.rotate();assert.equal(JSON.stringify(g.active.cells),original,'Four turns restore the shape');assert.equal(new Set(g.active.cells.map(p=>p.join(','))).size,4);while(g.move(-1)){}assert(g.fits(g.active));g.rotate();assert(g.fits(g.active),'Wall rotation cannot cross bounds');g.active.y=g.ghostY();g.rotate();assert(g.fits(g.active),'Floor rotation cannot cross bounds');}
for(const rows of [1,2,3,4]){g=new C.Game(random);g.start();for(let y=20-rows;y<20;y++)g.board[y].fill('Z');g.board[19][4]=null;g.active={type:'I',cells:[[0,0],[0,-1],[0,-2],[0,-3]],x:4,y:19};for(let y=20-rows;y<20;y++)g.board[y][4]=null;g.lock();assert.equal(g.status,'clearing');assert.equal(g.clearRows.length,rows);assert(!g.hardDrop(),'Cannot drop while rows are clearing');g.advance(200);g.advance(100);assert.equal(g.lines,rows);assert.equal(g.score,[0,100,300,500,800][rows]);assert.equal(g.status,'playing');assert.equal(g.board.length,20);assert.equal(g.board.flat().filter(Boolean).length,4-rows);}
g=new C.Game(random);g.start();const y=g.active.y;g.advance(200);g.advance(200);g.advance(200);g.advance(200);assert.equal(g.active.y,y);g.advance(100);assert.equal(g.active.y,y+1,'Gravity uses elapsed time');g.pause();const snapshot=JSON.stringify(g.active);g.advance(200);g.move(1);g.rotate();g.hardDrop();assert.equal(JSON.stringify(g.active),snapshot);g.resume();const landing=g.ghostY(),oldY=g.active.y;assert(g.hardDrop());assert.equal(g.score,(landing-oldY)*2);assert.equal(g.board.flat().filter(Boolean).length,4);
g=new C.Game(random);g.start();g.active.y=g.ghostY();for(let i=0;i<4;i++)g.advance(100);assert.equal(g.board.flat().filter(Boolean).length,0,'Lock delay allows adjustment');g.advance(100);assert.equal(g.board.flat().filter(Boolean).length,4);
g=new C.Game(random);g.start();g.board[0].fill('O');g.spawn();assert.equal(g.status,'over');assert(!g.move(1));g.reset();assert.equal(g.status,'ready');assert.equal(g.lines,0);assert(g.board.flat().every(v=>!v));
for(let trial=0;trial<100;trial++){g=new C.Game(random);g.start();for(let n=0;n<100&&g.status!=='over';n++){for(let i=0;i<Math.floor(random()*4);i++)g.rotate();for(let i=0;i<Math.floor(random()*8);i++)g.move(random()<.5?-1:1);g.hardDrop();while(g.status==='clearing')g.advance(200);assert(g.board.every(r=>r.length===10));assert(g.board.flat().every(v=>v===null||Object.hasOwn(C.SHAPES,v)));if(g.status==='playing')assert(g.fits(g.active));}assert(Number.isFinite(g.score));}
const hosting=JSON.parse(fs.readFileSync('vercel.json','utf8'));for(const route of ['/blocks','/blocks/'])assert(hosting.rewrites.some(r=>r.source===route&&r.destination==='/blocks.html'));assert(require('./build.cjs').files.includes('assets/blocks-background.webp'));
const {createServer}=require('./serve.cjs'),{once}=require('node:events');(async()=>{const server=createServer();try{server.listen(0,'127.0.0.1');await once(server,'listening');const url='http://127.0.0.1:'+server.address().port;for(const route of ['/blocks','/blocks/','/blocks.html']){const r=await fetch(url+route);assert.equal(r.status,200);assert.match(await r.text(),/id="blocksBoard"/)}for(const file of ['blocks-engine.js','blocks-ui.js','blocks.css','blocks-background.webp'])assert.equal((await fetch(url+'/assets/'+file)).status,200);console.log('PASS blocks: seven-piece bags, legal wall/floor rotations, gravity/lock delay, 1–4 row clears and scoring, pause, top-out, 100 randomized games and public routes.')}finally{server.closeAllConnections();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
