const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),m={exports:{}};
vm.runInNewContext(fs.readFileSync('assets/abacus-engine.js','utf8'),{module:m});const E=m.exports;
for(let col=0;col<5;col++)for(let digit=0;digit<10;digit++){const s=E.create();if(digit>=5)E.move(s,col,0);if(digit%5)E.move(s,col,digit%5);assert.equal(E.value(s),digit*10**(4-col));assert.equal(s.result,null);}
const s=E.create();assert.equal(E.check(s),null);E.setProblem(s,'12','+','7');E.move(s,4,4);assert.equal(s.result,null);assert.equal(E.check(s),false);E.move(s,3,1);E.move(s,4,0);assert.equal(E.value(s),19);assert.equal(s.result,null);assert.equal(E.check(s),true);E.clear(s);assert.equal(E.value(s),0);assert.equal(s.problem.answer,19);assert.equal(s.result,null);
for(const args of [['','',''],['1.2','+','3'],['-1','+','4'],['1e2','+','1'],['1','-','2'],['99999','+','1'],['1','*','2']])assert.throws(()=>E.setProblem(s,...args));
E.setProblem(s,'99999','-','99999');assert.equal(E.check(s),true);E.setProblem(s,'99999','+','0');s.digits.fill(9);assert.equal(E.check(s),true);E.free(s);assert.equal(E.value(s),99999);assert.equal(E.check(s),null);
const nodes=new Map();function el(){return {textContent:'',checked:false,value:'',disabled:false,style:{},dataset:{},attrs:{},events:{},children:[],setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,f){this.events[k]=f;},append(...items){this.children.push(...items);}};}function node(id){if(!nodes.has(id))nodes.set(id,el());return nodes.get(id);}
node('first').value='12';node('second').value='7';const effectTimers=new Map();let effectTimerId=0;const document={getElementById:node,createElement:el};vm.runInNewContext(fs.readFileSync('assets/abacus-ui.js','utf8'),{window:{AbacusPractice:E},document,setTimeout(fn){effectTimers.set(++effectTimerId,fn);return effectTimerId;},clearTimeout(id){effectTimers.delete(id);}});
const click=id=>node(id).events.click(),submit=()=>node('problemForm').events.submit({preventDefault(){}});
assert.equal(node('field').children.length,5);assert.equal(node('check').disabled,true);submit();assert.equal(node('check').disabled,false);assert.equal(node('value').textContent,'0');
const bead=(col,i)=>node('field').children[col].children[i].events.click();
bead(3,1);bead(4,4);bead(4,0);assert.equal(node('value').textContent,'19');assert.notEqual(node('feedback').dataset.kind,'success');click('check');assert.equal(node('feedback').dataset.kind,'success');bead(4,0);assert.equal(node('feedback').dataset.kind,'');click('check');assert.equal(node('feedback').dataset.kind,'retry');bead(4,0);click('check');assert.equal(node('feedback').dataset.kind,'success');
click('clear');assert.equal(node('value').textContent,'0');assert(node('question').textContent.includes('12'));node('first').value='3';node('first').events.input();assert.equal(node('check').disabled,true);node('subtract').checked=true;submit();assert(node('formError').textContent);assert.equal(node('check').disabled,true);node('second').value='2';submit();assert.equal(node('check').disabled,false);bead(4,1);click('check');assert.equal(node('feedback').dataset.kind,'success');click('free');assert.equal(node('check').disabled,true);assert.equal(node('value').textContent,'1');
console.log('PASS: all digits/places, explicit-only checking, unlimited retry, clear retains problem, free practice, input validation and real UI controls.');
node('problemDialog').showModal=function(){this.open=true;};node('problemDialog').close=function(){this.open=false;this.events.close();};node('openProblem').focus=()=>{};
click('openProblem');assert.equal(node('problemDialog').open,true);node('first').value='9';node('first').events.input();click('closeProblem');assert.equal(node('first').value,'3');assert.equal(node('problemDialog').open,false);assert.equal(node('value').textContent,'1');
click('openProblem');submit();assert.equal(node('problemDialog').open,false);assert.equal(node('check').disabled,false);click('openProblem');node('first').value='-1';submit();assert.equal(node('problemDialog').open,true);click('closeProblem');assert.equal(node('check').disabled,false);click('openProblem');click('free');assert.equal(node('problemDialog').open,false);
console.log('PASS: question dialog opens, cancels drafts without losing beads, stays open on invalid input, and closes on valid question or free practice.');
for(const limit of [10,20,100,1000,99999])for(const op of ['+','-','mixed']){const r=E.create();let previous='';for(let i=0;i<500;i++){E.randomProblem(r,limit,op);const p=r.problem;assert(p.a>=0&&p.a<=limit&&p.b>=0&&p.b<=limit&&p.answer>=1&&p.answer<=limit);if(op!=='mixed')assert.equal(p.op,op);assert.notEqual(JSON.stringify(p),previous);previous=JSON.stringify(p);assert.equal(E.value(r),0);assert.equal(r.result,null);}}
for(const edge of [0,.5,.999999999])for(const op of ['+','-','mixed']){const r=E.create();E.randomProblem(r,10,op,()=>edge);const before=JSON.stringify(r.problem);E.randomProblem(r,10,op,()=>edge);assert.notEqual(JSON.stringify(r.problem),before);assert(r.problem.answer>=1&&r.problem.answer<=10);}
click('computerSource');assert.equal(node('problemForm').hidden,true);assert.equal(node('computerForm').hidden,false);node('autoLimit').value='10';node('autoOperation').value='+';click('openProblem');node('computerForm').events.submit({preventDefault(){}});assert.equal(node('problemDialog').open,false);assert.equal(node('questionLabel').textContent,'電腦出題');assert.equal(node('check').textContent,'確認答案');
const questionBefore=node('question').textContent,nums=questionBefore.match(/\d+/g).map(Number),answer=nums[0]+nums[1];
click('clear');for(let c=0;c<5;c++){const d=Number(String(answer).padStart(5,'0')[c]);if(d>=5)bead(c,0);if(d%5)bead(c,d%5);}assert.equal(node('check').textContent,'確認答案');click('check');assert.equal(node('check').textContent,'下一題');assert.equal(node('question').textContent,questionBefore);click('check');assert.notEqual(node('question').textContent,questionBefore);assert.equal(node('value').textContent,'0');assert.equal(node('check').textContent,'確認答案');click('free');assert.equal(node('check').disabled,true);click('manualSource');assert.equal(node('problemForm').hidden,false);
console.log('PASS: 7,500 random problems respect bounds/operations, do not repeat consecutively, and require explicit confirmation before next question.');
node('first').value='1';node('second').value='0';node('subtract').checked=false;submit();click('check');assert.equal(node('answerEffect').hidden,false);assert.equal(node('answerEffect').dataset.kind,'retry');assert.equal(effectTimers.size,1);click('check');assert.equal(effectTimers.size,1);bead(4,1);assert.equal(node('answerEffect').hidden,true);assert.equal(effectTimers.size,0);click('check');assert.equal(node('answerEffect').dataset.kind,'success');assert.equal(node('effectLabel').textContent,'答對了！');for(const fn of [...effectTimers.values()])fn();assert.equal(node('answerEffect').hidden,true);assert.equal(effectTimers.size,0);click('check');click('openProblem');assert.equal(node('answerEffect').hidden,true);click('closeProblem');
console.log('PASS: correct/wrong effects appear only on confirmation, replace repeated effects, auto-dismiss, and clear on editing or opening settings.');
