const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const box={exports:{}};vm.runInNewContext(fs.readFileSync('assets/vault-engine.js','utf8'),{module:box});const E=box.exports;
for(const count of E.LEVELS)for(let run=0;run<80;run++){
 let s=E.create(count);assert.equal(s.code.length,count);assert.ok(s.code.every(c=>[-1,1].includes(c.dir)&&c.steps>=1&&c.steps<=9));
 assert.equal(E.act(s,{type:'turn',dir:1},2000).state.draft,0);s=E.act(s,{type:'ready'},2000).state;
 for(const c of s.code){for(let j=0;j<c.steps;j++)s=E.act(s,{type:'turn',dir:c.dir},2000).state;s=E.act(s,{type:'confirm'},2000).state;}
 assert.equal(s.phase,'won');assert.equal(s.doors,1);assert.equal(s.streak,1);const score=s.score;s=E.act(s,{type:'confirm'},2001).state;assert.equal(s.score,score,'Cannot award twice');
 const next=E.act(s,{type:'next'},3000).state;assert.equal(next.phase,'listening');assert.equal(next.round,2);assert.notDeepEqual(next.code,s.code);assert.equal(next.score,score);
}
let s=E.create(3,()=>.4);s.code=[{dir:-1,steps:7},{dir:-1,steps:3},{dir:1,steps:4}];s=E.act(s,{type:'ready'},0).state;
for(const c of s.code){for(let i=0;i<c.steps;i++)s=E.act(s,{type:'turn',dir:c.dir},0).state;s=E.act(s,{type:'confirm'},0).state;}assert.equal(s.phase,'won','Adjacent left instructions require separate confirmations');assert.equal(s.angle,-108);
let wrong=E.act(E.create(),{type:'ready'},0).state;wrong.code=[{dir:1,steps:9},{dir:1,steps:9},{dir:1,steps:9}];
for(let attempt=0;attempt<3;attempt++){const at=attempt*1000;wrong=E.act(wrong,{type:'turn',dir:-1},at).state;wrong=E.act(wrong,{type:'confirm'},at).state;assert.equal(wrong.hp,2-attempt);assert.equal(E.act(wrong,{type:'turn',dir:-1},at+10).state.draft,0,'Wrong-answer cooldown blocks repeated input');}assert.equal(wrong.phase,'lost');
let paused=E.act(E.create(),{type:'ready'},0).state;paused=E.act(paused,{type:'pause'},10000).state;const remaining=paused.remaining;paused=E.act(paused,{type:'tick'},999999).state;assert.equal(paused.remaining,remaining);paused=E.act(paused,{type:'resume'},999999).state;paused=E.act(paused,{type:'tick'},1000999).state;assert.equal(paused.remaining,remaining-1000);
let replay=E.act(E.create(),{type:'ready'},0).state;for(let i=0;i<2;i++){replay=E.act(replay,{type:'replay'},0).state;assert.equal(replay.phase,'listening');replay=E.act(replay,{type:'ready'},0).state;}assert.equal(replay.remaining,65000);assert.equal(E.act(replay,{type:'replay'},0).state.phase,'input');assert.equal(replay.replays,0);
const timeout=E.act(E.act(E.create(),{type:'ready'},0).state,{type:'turn',dir:1},75000).state;assert.equal(timeout.phase,'lost');assert.equal(timeout.draft,0);
let text=E.act(E.create(),{type:'visual'}).state;assert.equal(text.assisted,true);text=E.act(text,{type:'ready'},0).state;for(const c of text.code){for(let i=0;i<c.steps;i++)text=E.act(text,{type:'turn',dir:c.dir},0).state;text=E.act(text,{type:'confirm'},0).state;}assert.equal(text.award,250,'Visual fallback is clearly assisted and earns half points');
assert.equal(E.delta(179,-179),2);assert.equal(E.delta(-179,179),-2);assert.throws(()=>E.create(4));
console.log('PASS: vault sequences, adjacent directions, timed phases, exact steps, limited replay, cooldown, shield loss, assisted score and terminal awards.');

function boot(){
 const nodes=new Map(),timers=new Map(),events={},docEvents={},storage=new Map(),audioEvents=[];let time=0,id=0,speechResolve=null,doc;
 function el(){const classes=new Set();return {children:[],dataset:{},style:{setProperty(k,v){this[k]=v}},hidden:false,disabled:false,checked:true,open:false,clientHeight:240,textContent:'',attributes:{},className:'',classList:{add(...cs){cs.forEach(c=>classes.add(c))},remove(...cs){cs.forEach(c=>classes.delete(c))},toggle(c,on){on?classes.add(c):classes.delete(c)},contains(c){return classes.has(c)}},append(...ns){this.children.push(...ns)},appendChild(n){this.children.push(n);return n},replaceChildren(...ns){this.children=[...ns]},setAttribute(k,v){this.attributes[k]=v},getAttribute(k){return this.attributes[k]},addEventListener(k,v){this['on-'+k]=v},click(){if(!this.disabled)this.onclick?.()},focus(){doc.activeElement=this},scrollIntoView(){},showModal(){this.open=true},close(){this.open=false},setPointerCapture(){},getBoundingClientRect(){return {left:0,top:0,width:200,height:200}}};}
 const get=k=>{if(!nodes.has(k))nodes.set(k,el());return nodes.get(k)};const rings=[el(),el()],bars=Array.from({length:12},el);doc={body:el(),hidden:false,createElement:el,getElementById:get,querySelectorAll(s){return s==='.ticks'?rings:bars},addEventListener(k,v){docEvents[k]=v}};
 const math=Object.create(Math);math.random=()=>.4;const root={VaultEngine:{...E,create:count=>E.create(count,()=>.4)},VaultAudio:{create(){return {speak(code){audioEvents.push(code);return new Promise(resolve=>speechResolve=resolve)},stopSpeech(){speechResolve?.(false)},unlock(){return Promise.resolve(true)},stop(){speechResolve?.(false)},effect(){},setEnabled(){},dispose(){speechResolve?.(false)}}}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},addEventListener(k,v){events[k]=v},matchMedia(){return {matches:true}}};
 vm.runInNewContext(fs.readFileSync('assets/vault-ui.js','utf8'),{window:root,document:doc,Math:math,performance:{now:()=>time},setTimeout(fn,delay){const k=++id;timers.set(k,{fn,at:time+delay});return k},clearTimeout(k){timers.delete(k)}});
 return {get,doc,docEvents,events,audioEvents,storage,resolveSpeech(ok=true){speechResolve(ok)},step(ms){time+=ms;for(const [k,t] of [...timers])if(t.at<=time){timers.delete(k);t.fn();}},turn(dir,n){for(let i=0;i<n;i++)get(dir<0?'left':'right').click();},confirm(){get('confirm').click();}};
}
function bootAudio({supported=true}={}){const timers=new Map(),utterances=[],context=[];let id=0,report='',cancel=0;const root={navigator:{audioSession:{type:'ambient'}},setTimeout(fn){timers.set(++id,fn);return id},clearTimeout(k){timers.delete(k)},AudioContext:class{constructor(){this.state='interrupted';context.push(this)}resume(){this.state='running';return Promise.resolve()}suspend(){this.state='suspended';return Promise.resolve()}close(){this.state='closed';return Promise.resolve()}}};if(supported){root.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};root.speechSynthesis={cancel(){cancel++},resume(){},getVoices(){return [{lang:'en-US'},{lang:'zh-TW'}]},speak(u){utterances.push(u)}};}const b={exports:{}};vm.runInNewContext(fs.readFileSync('assets/vault-audio.js','utf8'),{window:root,module:b});return {sound:b.exports.create(v=>report=v),root,timers,utterances,context,get report(){return report},get cancel(){return cancel}};}
(async()=>{
 const ui=boot();assert.equal(ui.audioEvents.length,0);ui.get('start').click();assert.equal(ui.audioEvents.length,1,'Start triggers speech immediately');assert.equal(ui.get('entry').hidden,true);ui.step(30000);assert.equal(ui.get('clock').textContent,'01:15');ui.resolveSpeech();await Promise.resolve();await Promise.resolve();assert.equal(ui.get('entry').hidden,false);assert.equal(ui.get('codePreview').textContent,'');assert.equal(ui.get('confirm').disabled,true);
 ui.turn(-1,4);ui.confirm();assert.equal(ui.get('instructionTitle').textContent,'第 2 / 3 組指令');ui.turn(-1,4);ui.confirm();ui.turn(-1,4);ui.confirm();assert.equal(ui.get('result').hidden,false);assert.equal(ui.get('next').hidden,false);assert.equal(ui.get('score').textContent,'500');assert.equal(ui.storage.size,1);ui.get('next').click();assert.equal(ui.audioEvents.length,2);assert.equal(ui.get('entry').hidden,true);
 ui.get('pause').click();ui.resolveSpeech();await Promise.resolve();assert.equal(ui.get('modal').open,true);assert.equal(ui.get('codePreview').textContent,'');ui.get('resume').click();assert.equal(ui.audioEvents.length,3,'Resume during speech requests the sequence again');ui.resolveSpeech(false);await Promise.resolve();await Promise.resolve();assert.equal(ui.get('retrySpeech').hidden,false);ui.get('useText').click();assert.equal(ui.get('textReady').hidden,false);assert.notEqual(ui.get('codePreview').textContent,'');ui.get('textReady').click();assert.equal(ui.get('codePreview').textContent,'');ui.doc.hidden=true;ui.docEvents.visibilitychange();const frozen=ui.get('clock').textContent;ui.step(999999);assert.equal(ui.get('clock').textContent,frozen);assert.equal(ui.get('modal').open,true);ui.get('exit').click();assert.equal(ui.get('home').hidden,false);
 const pointer=boot();pointer.get('start').click();pointer.resolveSpeech();await Promise.resolve();await Promise.resolve();pointer.get('dial')['on-pointerdown']({button:0,pointerId:1,clientX:100,clientY:0,preventDefault(){}});pointer.get('dial')['on-pointermove']({pointerId:1,clientX:131,clientY:5,preventDefault(){}});assert.match(pointer.get('draft').textContent,/右轉.*1 步/);pointer.get('clear').click();assert.equal(pointer.get('draft').textContent,'尚未轉動');
 console.log('PASS: real vault UI locks during speech, hides answers during input, wins and continues, pauses safely, handles failed voice/text fallback and supports pointer rotation.');
 const a=bootAudio();assert.equal(a.context.length,0);await a.sound.unlock();assert.equal(a.root.navigator.audioSession.type,'playback');assert.equal(a.context[0].state,'running');const p=a.sound.speak([{dir:-1,steps:7},{dir:-1,steps:3},{dir:1,steps:4}]);assert.equal(a.utterances[0].text,'左，七。左，三。右，四。');assert.equal(a.utterances[0].rate,.65);assert.equal(a.utterances[0].pitch,.82);assert.equal(a.utterances[0].voice.lang,'zh-TW');a.utterances[0].onend();assert.equal(await p,true);assert.equal(a.timers.size,0);
 const pending=a.sound.speak([{dir:1,steps:1}]);const stale=a.utterances.at(-1);a.sound.stopSpeech();assert.equal(await pending,false);stale.onend();assert.equal(a.timers.size,0);
 const hung=a.sound.speak([{dir:1,steps:1}]);for(const f of [...a.timers.values()])f();assert.equal(await hung,false);assert.match(a.report,/重試/);const failing=a.sound.speak([{dir:1,steps:1}]);a.utterances.at(-1).onerror();assert.equal(await failing,false);a.sound.dispose();assert.equal(a.context[0].state,'closed');
 const unavailable=bootAudio({supported:false});assert.equal(await unavailable.sound.speak([]),false);assert.match(unavailable.report,/文字/);
 console.log('PASS: iPad playback policy, interrupted-context resume, Traditional Chinese TTS, end gating, cancellation, failed/timeout speech and missing API fallback.');
})().catch(error=>{console.error(error);process.exitCode=1});
