const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const box={exports:{}};vm.runInNewContext(fs.readFileSync('assets/memory-engine.js','utf8'),{module:box});const E=box.exports;let seed=7;const rng=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
for(const size of E.COUNTS)for(let run=0;run<20;run++){
 let s=E.create(size,rng,0),now=0;assert.equal(s.deck.length,size);const ids=[...new Set(s.deck)];assert.equal(ids.length,size/2);assert.ok(ids.every(id=>s.deck.filter(x=>x===id).length===2));assert.equal(s.remainingMs,E.SECONDS[size]*1000);
 for(const id of ids){const pair=s.deck.map((x,i)=>x===id?i:-1).filter(i=>i>=0);s=E.act(s,{type:'flip',index:pair[0]},now).state;const same=E.act(s,{type:'flip',index:pair[0]},now);assert.equal(same.state.flips,s.flips);s=E.act(s,{type:'flip',index:pair[1]},now).state;now+=650;s=E.act(s,{type:'tick'},now).state;}
 assert.equal(s.phase,'won');assert.equal(s.flips,size);assert.equal(s.attempts,size/2);assert.equal(s.combo,size/2);assert.equal(s.matched.length,size);assert.equal(s.shields,E.SHIELDS[size]);const terminal=E.act(s,{type:'flip',index:0},now+999999);assert.equal(terminal.state.score,s.score);assert.equal(terminal.state.phase,'won');assert.equal(terminal.effects.length,0);
}
let s=E.create(16,()=>0,0),first=0,other=s.deck.findIndex(x=>x!==s.deck[first]);s=E.act(s,{type:'flip',index:first},0).state;s=E.act(s,{type:'flip',index:other},0).state;assert.equal(s.phase,'resolving');const third=s.deck.findIndex((_,i)=>i!==first&&i!==other);s=E.act(s,{type:'flip',index:third},100).state;assert.equal(s.open.length,2);assert.equal(s.flips,2);
s=E.act(s,{type:'pause'},500).state;const left=s.remainingMs,reveal=s.revealMs;s=E.act(s,{type:'tick'},200000).state;assert.equal(s.remainingMs,left);assert.equal(s.revealMs,reveal);s=E.act(s,{type:'resume'},200000).state;s=E.act(s,{type:'tick'},200600).state;assert.equal(s.open.length,0);assert.equal(s.shields,15);assert.equal(s.combo,0);
let dying=E.create(16,()=>0,0);dying.shields=1;dying=E.act(dying,{type:'flip',index:first},0).state;dying=E.act(dying,{type:'flip',index:other},0).state;const ended=E.act(dying,{type:'tick'},1100);assert.equal(ended.state.phase,'lost');assert.equal(ended.state.reason,'shield');assert.equal(ended.state.shields,0);assert.equal(ended.effects.filter(e=>e.kind==='lost').length,1);
const timed=E.act(E.create(52,rng,0),{type:'flip',index:0},300000);assert.equal(timed.state.phase,'lost');assert.equal(timed.state.reason,'time');assert.equal(timed.state.flips,0);assert.throws(()=>E.create(18));
const last=E.create(16,()=>0,0);last.matched=last.deck.map((_,i)=>i).filter(i=>last.deck[i]!==last.deck[0]);last.remainingMs=1;const lastPair=last.deck.map((id,i)=>id===last.deck[0]?i:-1).filter(i=>i>=0);const one=E.act(last,{type:'flip',index:lastPair[0]},0).state;assert.equal(E.act(one,{type:'flip',index:lastPair[1]},0).state.phase,'won','Last pair completes before the animation even with less than one second left');
console.log('PASS: all five deck sizes contain exact pairs; matches, combo scoring, click locks, timed failure, shield failure, pause/resume and terminal rewards behave correctly.');

function boot(options={}){const nodes=new Map(),frames=new Map(),timers=new Map(),events={},docEvents={},soundEvents=[],imageRequests=[],storage=options.storage||new Map();let now=0,id=0,document;function element(){let text='',className='';const cls=new Set();return {children:[],style:{setProperty(k,v){this[k]=String(v)},getPropertyValue(k){return this[k]||''}},dataset:{},attributes:{},hidden:false,disabled:false,checked:false,open:false,
 get className(){return className},set className(v){className=v},classList:{toggle(k,on){on?cls.add(k):cls.delete(k)},add(k){cls.add(k)},remove(k){cls.delete(k)},contains(k){return cls.has(k)}},
 appendChild(n){this.children.push(n);n.parentElement=this;return n},append(...ns){ns.forEach(n=>this.appendChild(n))},replaceChildren(...ns){text='';this.children=[];this.append(...ns)},setAttribute(k,v){this.attributes[k]=v},getAttribute(k){return this.attributes[k]},get textContent(){return text+this.children.map(c=>c.textContent).join('')},set textContent(v){text=String(v);this.children=[]},focus(){document.activeElement=this},scrollIntoView(){},click(){if(!this.disabled)this.onclick?.()},showModal(){this.open=true},close(){this.open=false},addEventListener(k,fn){this['event-'+k]=fn},getBoundingClientRect(){return {left:0,top:0,width:100,height:100}},getContext(){return null}};}
 const get=k=>{if(!nodes.has(k))nodes.set(k,element());return nodes.get(k)};document={body:element(),getElementById:get,createElement:element,createElementNS:element,addEventListener(k,fn){docEvents[k]=fn},hidden:false};get('timeValue').parentElement=element();get('memorySound').checked=true;get('memoryMusic').checked=true;const math=Object.create(Math);math.random=()=>.42;
 class SpriteImage{set src(value){this.url=value;imageRequests.push(this);if(!options.imagesPending){this.settled=true;this.onload();}}}
 vm.runInNewContext(fs.readFileSync('assets/memory-ui.js','utf8'),{window:{OrbitMemory:E,OrbitAudio:{create(){return {activate(){soundEvents.push(['activate']);return Promise.resolve();},play(v){soundEvents.push(['play',v])},setEnabled(v){soundEvents.push(['effects',v])},setMusic(v){soundEvents.push(['music',v])},startMusic(v){soundEvents.push(['start',v])},stopMusic(){soundEvents.push(['stop'])},setTension(v){soundEvents.push(['tension',v])},suspend(){soundEvents.push(['suspend'])},dispose(){soundEvents.push(['dispose'])}}}},Image:SpriteImage,localStorage:{getItem(key){if(options.storageBlocked)throw Error('Storage unavailable');return storage.get(key)||null},setItem(key,value){if(options.storageBlocked)throw Error('Storage unavailable');storage.set(key,value)}},innerWidth:390,innerHeight:844,devicePixelRatio:1,matchMedia(){return {matches:options.reduced!==false,addEventListener(){}}},addEventListener(k,fn){events[k]=fn}},document,Math:math,performance:{now:()=>now},requestAnimationFrame(fn){const key=++id;frames.set(key,fn);return key},cancelAnimationFrame(key){frames.delete(key)},setTimeout(fn,delay){const key=++id;timers.set(key,{fn,at:now+delay});return key},clearTimeout(key){timers.delete(key)}});
 return {get,docEvents,document,events,frames,soundEvents,imageRequests,storage,settleImages(ok=true){for(const img of imageRequests)if(!img.settled){img.settled=true;ok?img.onload():img.onerror();}},step(ms){now+=ms;const callbacks=[...frames.values()];frames.clear();callbacks.forEach(fn=>fn(now));for(const [key,t] of [...timers])if(t.at<=now){timers.delete(key);t.fn();}}};
}
for(const size of E.COUNTS){const ui=boot();ui.get('memoryCounts').children.find(b=>Number(b.dataset.count)===size).click();ui.get('memoryStart').click();assert.equal(ui.get('memoryGrid').children.length,size);assert.equal(ui.get('setupShield').textContent,String(E.SHIELDS[size]));assert.equal(ui.get('shieldValue').textContent,E.SHIELDS[size]+'/'+E.SHIELDS[size]);assert.equal(ui.get('setupTime').textContent, String(Math.floor(E.SECONDS[size]/60)).padStart(2,'0')+':'+String(E.SECONDS[size]%60).padStart(2,'0'));ui.get('memoryPause').click();const before=ui.get('timeValue').textContent;ui.step(300000);assert.equal(ui.get('timeValue').textContent,before);assert.equal(ui.get('missionDialog').open,true);ui.get('dialogResume').click();ui.step(1000);assert.notEqual(ui.get('timeValue').textContent,before);ui.document.hidden=true;ui.docEvents.visibilitychange();assert.equal(ui.get('missionDialog').open,true);}
const ui=boot();ui.get('memoryStart').click();const deck=E.create(16,()=>.42,0).deck;for(const id of new Set(deck)){for(let i=0;i<deck.length;i++)if(deck[i]===id)ui.get('memoryGrid').children[i].click();ui.step(650);}ui.step(1);assert.match(ui.get('dialogTitle').textContent,/重新上線/);assert.equal(ui.get('missionDialog').open,true);ui.get('dialogRestart').click();assert.equal(ui.get('flipsValue').textContent,'0');assert.equal(ui.get('scoreValue').textContent,'0');ui.step(180000);assert.match(ui.get('dialogTitle').textContent,/中止/);assert.equal(ui.get('missionDialog').open,true);
console.log('PASS: real memory UI starts all sizes, pauses and hides cards, resumes timing, auto-pauses in background, shows victory/timeout results and resets counters on restart.');
const themeKey='learning-planet-memory-theme-v1',themeUI=boot();
assert.equal(themeUI.document.body.dataset.cardTheme,'C');assert.equal(themeUI.get('memoryThemes').children.filter(b=>b.getAttribute('aria-pressed')==='true').length,1);
for(const theme of ['A','B','C']){themeUI.get('memoryThemes').children.find(b=>b.dataset.theme===theme).click();assert.equal(themeUI.document.body.dataset.cardTheme,theme);assert.equal(themeUI.storage.get(themeKey),theme);assert.equal(boot({storage:themeUI.storage}).document.body.dataset.cardTheme,theme);}
assert.equal(boot({storage:new Map([[themeKey,'invalid']])}).document.body.dataset.cardTheme,'C');
const denied=boot({storageBlocked:true});denied.get('memoryThemes').children[1].click();denied.get('memoryStart').click();assert.equal(denied.document.body.dataset.cardTheme,'B');assert.equal(denied.get('memoryGrid').children.length,16);
const allArt=boot();allArt.get('memoryCounts').children[4].click();allArt.get('memoryStart').click();const fullDeck=E.create(52,()=>.42,0).deck,bySymbol=new Map();
allArt.get('memoryGrid').children.forEach((card,i)=>{const sprite=card.children[0].children[1].children[1],appearance=sprite.className+'|'+sprite.style.backgroundPosition,id=fullDeck[i];if(bySymbol.has(id))assert.equal(appearance,bySymbol.get(id),'Matching cards must show identical equipment');else bySymbol.set(id,appearance);assert.match(card.getAttribute('aria-label'),/未翻開/);});
assert.equal(new Set(bySymbol.values()).size,26,'All 26 equipment symbols must have distinct artwork');
const waiting=boot({imagesPending:true});assert.equal(waiting.get('memoryStart').disabled,true);waiting.get('memoryStart').click();waiting.step(19000);assert.equal(waiting.get('memoryGrid').children.length,0);waiting.settleImages();assert.equal(waiting.get('memoryStart').disabled,false);waiting.get('memoryStart').click();assert.equal(waiting.get('timeValue').textContent,'03:00','Loading must not consume mission time');
const failedArt=boot({imagesPending:true});failedArt.settleImages(false);assert.equal(failedArt.get('memoryStart').getAttribute('aria-label'),'重新載入卡牌');failedArt.get('memoryStart').click();failedArt.settleImages();failedArt.get('memoryStart').click();assert.equal(failedArt.get('memoryGrid').children.length,16);
const stalledArt=boot({imagesPending:true});stalledArt.step(20000);assert.equal(stalledArt.get('memoryStart').disabled,false);assert.match(stalledArt.get('artworkStatus').textContent,/重試/);assert.equal(stalledArt.get('memoryGrid').children.length,0);
console.log('PASS: A/B/C theme selection defaults to C, persists safely, keeps 26 distinct matching images, and waits for artwork with retry on failure or timeout.');
const musicUI=boot();assert.equal(musicUI.soundEvents.length,0,'Home opens silently');musicUI.get('memoryStart').click();assert.ok(musicUI.soundEvents.some(([name,reset])=>name==='start'&&reset===true));musicUI.get('memoryMusic').checked=false;musicUI.get('memoryMusic').onchange();assert.deepEqual(musicUI.soundEvents.at(-1),['music',false]);musicUI.get('memoryPause').click();assert.equal(musicUI.soundEvents.at(-1)[0],'suspend');musicUI.get('dialogResume').click();assert.ok(musicUI.soundEvents.some(([name,reset])=>name==='start'&&reset===undefined));musicUI.step(170000);assert.ok(musicUI.soundEvents.some(([name,value])=>name==='tension'&&value>.7));musicUI.step(10000);assert.ok(musicUI.soundEvents.some(([name])=>name==='stop'));musicUI.get('dialogMenu').click();assert.equal(musicUI.soundEvents.at(-1)[0],'suspend');
console.log('PASS: game controls start music only in a mission, pause/resume with the game, update final-countdown tension and stop at results/menu.');
// The duration bounds preserve the original half-minute recommendations.
for(const seconds of [180,210,240,270,300,360,420,480,540,570,600]){
 const custom=E.create(24,()=>.42,0,seconds);assert.equal(E.act(custom,{type:'tick'},seconds*1000-1).state.phase,'playing');assert.equal(E.act(custom,{type:'tick'},seconds*1000).state.reason,'time');
}
for(const invalid of [0,179,601,Infinity,NaN,'300'])assert.throws(()=>E.create(16,()=>.42,0,invalid));
let unlimited=E.create(16,()=>.42,0,null);unlimited=E.act(unlimited,{type:'tick'},9999999).state;assert.equal(unlimited.remainingMs,null);assert.equal(unlimited.phase,'playing');
let unlimitedNow=9999999;for(const symbol of new Set(unlimited.deck)){for(const i of unlimited.deck.map((id,i)=>id===symbol?i:-1).filter(i=>i>=0))unlimited=E.act(unlimited,{type:'flip',index:i},unlimitedNow).state;unlimitedNow+=650;unlimited=E.act(unlimited,{type:'tick'},unlimitedNow).state;}
assert.equal(unlimited.phase,'won');assert.equal(unlimited.bonus,unlimited.shields*10);assert.ok(Number.isFinite(unlimited.score));
let noTimeShield=E.create(16,()=>.42,0,null);noTimeShield.shields=1;const different=noTimeShield.deck.findIndex(id=>id!==noTimeShield.deck[0]);noTimeShield=E.act(noTimeShield,{type:'flip',index:0},0).state;noTimeShield=E.act(noTimeShield,{type:'flip',index:different},0).state;assert.equal(E.act(noTimeShield,{type:'tick'},1100).state.reason,'shield');
const timeUI=boot();assert.equal(timeUI.get('timeMinus').disabled,true);for(let i=0;i<7;i++)timeUI.get('timePlus').click();assert.equal(timeUI.get('memoryTimeValue').textContent,'10:00');timeUI.get('timePlus').click();assert.equal(timeUI.get('setupTime').textContent,'∞');assert.equal(timeUI.get('timePlus').disabled,true);timeUI.get('timeMinus').click();assert.equal(timeUI.get('memoryTimeValue').textContent,'10:00');timeUI.get('timePlus').click();timeUI.get('memoryStart').click();timeUI.step(9999999);assert.equal(timeUI.get('timeValue').textContent,'∞');assert.equal(timeUI.get('missionDialog').open,false);assert.equal(timeUI.get('timeValue').parentElement.classList.contains('critical'),false);assert.equal(timeUI.soundEvents.filter(([name])=>name==='tension').at(-1)[1],0);
timeUI.get('memoryRestart').click();timeUI.get('dialogRestart').click();assert.equal(timeUI.get('timeValue').textContent,'∞','Retry retains the chosen duration');timeUI.get('memoryPause').click();timeUI.get('dialogMenu').click();timeUI.get('memoryCounts').children[1].click();assert.equal(timeUI.get('setupTime').textContent,'03:30');timeUI.get('timePlus').click();assert.equal(timeUI.get('setupTime').textContent,'04:30');timeUI.get('timeMinus').click();timeUI.get('timeMinus').click();assert.equal(timeUI.get('setupTime').textContent,'03:00');assert.equal(timeUI.get('timeMinus').disabled,true);
for(let i=0;i<7;i++)timeUI.get('timePlus').click();timeUI.get('memoryStart').click();assert.equal(timeUI.get('timeValue').textContent,'10:00');timeUI.step(600000);assert.equal(timeUI.get('missionDialog').dataset.outcome,'lost');
console.log('PASS: +/- duration controls keep recommended defaults, enforce 3–10 minutes, support unlimited time, retain retry settings, and preserve shield failure and finite scoring.');
function solveUI(app){const deck=E.create(16,()=>.42,0).deck;for(const symbol of new Set(deck)){for(let i=0;i<deck.length;i++)if(deck[i]===symbol)app.get('memoryGrid').children[i].click();app.step(650);}}
const intro=boot({reduced:false});intro.get('memoryStart').click();const originalCards=intro.get('memoryGrid').children;intro.get('memoryStart').click();assert.equal(intro.get('memoryGrid').children,originalCards,'Double launch cannot rebuild the mission');assert.equal(intro.get('launchDialog').open,true);intro.step(2399);assert.equal(intro.get('timeValue').textContent,'03:00');intro.get('memoryGrid').children[0].click();assert.equal(intro.get('flipsValue').textContent,'0','The deck is locked during arrival');intro.step(1);assert.equal(intro.get('launchDialog').open,false);assert.equal(intro.get('timeValue').textContent,'03:00');intro.step(1000);assert.equal(intro.get('timeValue').textContent,'02:59');
const skip=boot({reduced:false});skip.get('memoryStart').click();skip.step(400);skip.get('launchSkip').click();skip.get('memoryGrid').children[0].click();assert.equal(skip.get('flipsValue').textContent,'1');skip.step(2000);assert.equal(skip.get('flipsValue').textContent,'1','A canceled launch callback cannot restart the game');assert.equal(skip.get('timeValue').textContent,'02:58');
const escape=boot({reduced:false});escape.get('memoryStart').click();escape.events.keydown({key:'Escape',preventDefault(){}});assert.equal(escape.get('launchDialog').open,false);assert.equal(escape.get('missionDialog').open,false,'Escape skips arrival without opening pause');escape.get('memoryGrid').children[0].click();assert.equal(escape.get('flipsValue').textContent,'1');
for(const event of ['visibilitychange','pagehide']){const background=boot({reduced:false});background.get('memoryStart').click();if(event==='visibilitychange'){background.document.hidden=true;background.docEvents.visibilitychange();}else background.events.pagehide();background.step(300000);assert.equal(background.get('launchDialog').open,false);assert.match(background.get('dialogTitle').textContent,/暫停/);assert.equal(background.get('timeValue').textContent,'03:00');background.document.hidden=false;background.get('dialogResume').click();background.step(1000);assert.equal(background.get('timeValue').textContent,'02:59');}
const resultUI=boot({reduced:false});resultUI.get('memoryStart').click();resultUI.get('launchSkip').click();solveUI(resultUI);assert.equal(resultUI.get('missionDialog').open,false);assert.equal(resultUI.soundEvents.some(([name,kind])=>name==='play'&&kind==='won'),false,'End sound waits for the result animation');resultUI.step(50);assert.equal(resultUI.get('missionDialog').dataset.outcome,'won');assert.equal(resultUI.get('resultScene').hidden,false);assert.equal(resultUI.get('dialogRestart').hidden,false);assert.equal(resultUI.get('dialogMenu').hidden,false);resultUI.step(10000);assert.equal(resultUI.soundEvents.filter(([name,kind])=>name==='play'&&kind==='won').length,1);resultUI.get('dialogRestart').click();resultUI.get('launchSkip').click();resultUI.get('memoryPause').click();assert.equal(resultUI.get('resultScene').hidden,true,'Pause dialogs do not inherit the result illustration');
const stale=boot({reduced:false});stale.get('memoryStart').click();stale.get('launchSkip').click();stale.step(180000);stale.get('memoryRestart').click();stale.get('dialogRestart').click();stale.get('launchSkip').click();stale.step(700);assert.equal(stale.get('missionDialog').open,false);assert.equal(stale.soundEvents.some(([name,kind])=>name==='play'&&kind==='lost'),false,'A reset cancels the previous ending and its sound');
const hiddenResult=boot({reduced:false});hiddenResult.get('memoryStart').click();hiddenResult.get('launchSkip').click();hiddenResult.step(180000);hiddenResult.document.hidden=true;hiddenResult.docEvents.visibilitychange();hiddenResult.step(700);assert.equal(hiddenResult.get('missionDialog').dataset.outcome,'lost');assert.equal(hiddenResult.soundEvents.some(([name,kind])=>name==='play'&&kind==='lost'),false,'A delayed result does not make sound in a hidden tab');
console.log('PASS: arrival locks cards without consuming time, can be skipped, pauses on background, and result scenes/sounds synchronize once with safe restart cancellation.');
require('./test-memory-audio.cjs');
